package UserManagement.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_Configuration;
  private ConceptPresentation props_Entity;
  private ConceptPresentation props_EntityOperationHolder;
  private ConceptPresentation props_EntityRef;
  private ConceptPresentation props_Field;
  private ConceptPresentation props_FieldAnnotationHolder;
  private ConceptPresentation props_FieldTypeHolder;
  private ConceptPresentation props_Main;
  private ConceptPresentation props_Relation;
  private ConceptPresentation props_RelationOperationHolder;
  private ConceptPresentation props_RelationRef;
  private ConceptPresentation props_SqlSchem;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.Configuration:
        if (props_Configuration == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Configuration");
          props_Configuration = cpb.create();
        }
        return props_Configuration;
      case LanguageConceptSwitch.Entity:
        if (props_Entity == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Entity = cpb.create();
        }
        return props_Entity;
      case LanguageConceptSwitch.EntityOperationHolder:
        if (props_EntityOperationHolder == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("EntityOperationHolder");
          props_EntityOperationHolder = cpb.create();
        }
        return props_EntityOperationHolder;
      case LanguageConceptSwitch.EntityRef:
        if (props_EntityRef == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByReference(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f243a4ec1L, 0x6a6f5a6f243a4ec2L, "entity", "", "");
          props_EntityRef = cpb.create();
        }
        return props_EntityRef;
      case LanguageConceptSwitch.Field:
        if (props_Field == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Field = cpb.create();
        }
        return props_Field;
      case LanguageConceptSwitch.FieldAnnotationHolder:
        if (props_FieldAnnotationHolder == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("FieldAnnotationHolder");
          props_FieldAnnotationHolder = cpb.create();
        }
        return props_FieldAnnotationHolder;
      case LanguageConceptSwitch.FieldTypeHolder:
        if (props_FieldTypeHolder == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("FieldTypeHolder");
          props_FieldTypeHolder = cpb.create();
        }
        return props_FieldTypeHolder;
      case LanguageConceptSwitch.Main:
        if (props_Main == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Main = cpb.create();
        }
        return props_Main;
      case LanguageConceptSwitch.Relation:
        if (props_Relation == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Relation = cpb.create();
        }
        return props_Relation;
      case LanguageConceptSwitch.RelationOperationHolder:
        if (props_RelationOperationHolder == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("RelationOperationHolder");
          props_RelationOperationHolder = cpb.create();
        }
        return props_RelationOperationHolder;
      case LanguageConceptSwitch.RelationRef:
        if (props_RelationRef == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByReference(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f243a4ec5L, 0x6a6f5a6f243a4ec6L, "relation", "", "");
          props_RelationRef = cpb.create();
        }
        return props_RelationRef;
      case LanguageConceptSwitch.SqlSchem:
        if (props_SqlSchem == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_SqlSchem = cpb.create();
        }
        return props_SqlSchem;
    }
    return null;
  }
}
