package UserManagement.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_Entity;
  private ConceptPresentation props_EntityOperationHolder;
  private ConceptPresentation props_Field;
  private ConceptPresentation props_FieldAnotationHolder;
  private ConceptPresentation props_FieldTypeHolder;
  private ConceptPresentation props_NatsServer;
  private ConceptPresentation props_Relation;
  private ConceptPresentation props_RelationOperationHolder;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.Entity:
        if (props_Entity == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Entity = cpb.create();
        }
        return props_Entity;
      case LanguageConceptSwitch.EntityOperationHolder:
        if (props_EntityOperationHolder == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("EntityOperationHolder");
          props_EntityOperationHolder = cpb.create();
        }
        return props_EntityOperationHolder;
      case LanguageConceptSwitch.Field:
        if (props_Field == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("f");
          props_Field = cpb.create();
        }
        return props_Field;
      case LanguageConceptSwitch.FieldAnotationHolder:
        if (props_FieldAnotationHolder == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("FieldAnotationHolder");
          props_FieldAnotationHolder = cpb.create();
        }
        return props_FieldAnotationHolder;
      case LanguageConceptSwitch.FieldTypeHolder:
        if (props_FieldTypeHolder == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("FieldTypeHolder");
          props_FieldTypeHolder = cpb.create();
        }
        return props_FieldTypeHolder;
      case LanguageConceptSwitch.NatsServer:
        if (props_NatsServer == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_NatsServer = cpb.create();
        }
        return props_NatsServer;
      case LanguageConceptSwitch.Relation:
        if (props_Relation == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Relation = cpb.create();
        }
        return props_Relation;
      case LanguageConceptSwitch.RelationOperationHolder:
        if (props_RelationOperationHolder == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("RelationOperationHolder");
          props_RelationOperationHolder = cpb.create();
        }
        return props_RelationOperationHolder;
    }
    return null;
  }
}
