package UserManagement.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_RelationOperation extends EnumerationDescriptorBase {

  public EnumerationDescriptor_RelationOperation() {
    super(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac61L, "RelationOperation", "r:a3a366a2-da30-48fe-b644-04a6d92b06a4(UserManagement.structure)/7669448123827596385");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_assign_0 = new EnumerationDescriptor.MemberDescriptor("assign", "assign", 0x6a6f5a6f2407ac62L, "r:a3a366a2-da30-48fe-b644-04a6d92b06a4(UserManagement.structure)/7669448123827596386");
  private final EnumerationDescriptor.MemberDescriptor myMember_remove_0 = new EnumerationDescriptor.MemberDescriptor("remove", "remove", 0x6a6f5a6f2407ac64L, "r:a3a366a2-da30-48fe-b644-04a6d92b06a4(UserManagement.structure)/7669448123827596388");
  private final EnumerationDescriptor.MemberDescriptor myMember_list_0 = new EnumerationDescriptor.MemberDescriptor("list", "list", 0x6a6f5a6f2407ac66L, "r:a3a366a2-da30-48fe-b644-04a6d92b06a4(UserManagement.structure)/7669448123827596390");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac61L, 0x6a6f5a6f2407ac62L, 0x6a6f5a6f2407ac64L, 0x6a6f5a6f2407ac66L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList0(myIndex, myMember_assign_0, myMember_remove_0, myMember_list_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "assign":
        return myMember_assign_0;
      case "remove":
        return myMember_remove_0;
      case "list":
        return myMember_list_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
