package UserManagement.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_EntityOperation extends EnumerationDescriptorBase {

  public EnumerationDescriptor_EntityOperation() {
    super(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac57L, "EntityOperation", "r:a3a366a2-da30-48fe-b644-04a6d92b06a4(UserManagement.structure)/7669448123827596375");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_create_0 = new EnumerationDescriptor.MemberDescriptor("create", "create", 0x6a6f5a6f2407ac58L, "r:a3a366a2-da30-48fe-b644-04a6d92b06a4(UserManagement.structure)/7669448123827596376");
  private final EnumerationDescriptor.MemberDescriptor myMember_update_0 = new EnumerationDescriptor.MemberDescriptor("update", "update", 0x6a6f5a6f2407ac5aL, "r:a3a366a2-da30-48fe-b644-04a6d92b06a4(UserManagement.structure)/7669448123827596378");
  private final EnumerationDescriptor.MemberDescriptor myMember_delete_0 = new EnumerationDescriptor.MemberDescriptor("delete", "delete", 0x6a6f5a6f2407ac5bL, "r:a3a366a2-da30-48fe-b644-04a6d92b06a4(UserManagement.structure)/7669448123827596379");
  private final EnumerationDescriptor.MemberDescriptor myMember_list_0 = new EnumerationDescriptor.MemberDescriptor("list", "list", 0x6a6f5a6f2407ac5cL, "r:a3a366a2-da30-48fe-b644-04a6d92b06a4(UserManagement.structure)/7669448123827596380");
  private final EnumerationDescriptor.MemberDescriptor myMember_get_0 = new EnumerationDescriptor.MemberDescriptor("get", "get", 0x6a6f5a6f2407ac5eL, "r:a3a366a2-da30-48fe-b644-04a6d92b06a4(UserManagement.structure)/7669448123827596382");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac57L, 0x6a6f5a6f2407ac58L, 0x6a6f5a6f2407ac5aL, 0x6a6f5a6f2407ac5bL, 0x6a6f5a6f2407ac5cL, 0x6a6f5a6f2407ac5eL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList0(myIndex, myMember_create_0, myMember_update_0, myMember_delete_0, myMember_list_0, myMember_get_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "create":
        return myMember_create_0;
      case "update":
        return myMember_update_0;
      case "delete":
        return myMember_delete_0;
      case "list":
        return myMember_list_0;
      case "get":
        return myMember_get_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
