package UserManagement.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptEntity = createDescriptorForEntity();
  /*package*/ final ConceptDescriptor myConceptEntityOperationHolder = createDescriptorForEntityOperationHolder();
  /*package*/ final ConceptDescriptor myConceptEntityRef = createDescriptorForEntityRef();
  /*package*/ final ConceptDescriptor myConceptField = createDescriptorForField();
  /*package*/ final ConceptDescriptor myConceptFieldAnnotationHolder = createDescriptorForFieldAnnotationHolder();
  /*package*/ final ConceptDescriptor myConceptFieldTypeHolder = createDescriptorForFieldTypeHolder();
  /*package*/ final ConceptDescriptor myConceptNatsServer = createDescriptorForNatsServer();
  /*package*/ final ConceptDescriptor myConceptRelation = createDescriptorForRelation();
  /*package*/ final ConceptDescriptor myConceptRelationOperationHolder = createDescriptorForRelationOperationHolder();
  /*package*/ final ConceptDescriptor myConceptRelationRef = createDescriptorForRelationRef();
  /*package*/ final ConceptDescriptor myConceptSqlSchem = createDescriptorForSqlSchem();
  /*package*/ final EnumerationDescriptor myEnumerationEntityOperation = new EnumerationDescriptor_EntityOperation();
  /*package*/ final EnumerationDescriptor myEnumerationFieldAnnotation = new EnumerationDescriptor_FieldAnnotation();
  /*package*/ final EnumerationDescriptor myEnumerationFieldType = new EnumerationDescriptor_FieldType();
  /*package*/ final EnumerationDescriptor myEnumerationRelationOperation = new EnumerationDescriptor_RelationOperation();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptEntity, myConceptEntityOperationHolder, myConceptEntityRef, myConceptField, myConceptFieldAnnotationHolder, myConceptFieldTypeHolder, myConceptNatsServer, myConceptRelation, myConceptRelationOperationHolder, myConceptRelationRef, myConceptSqlSchem);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Entity:
        return myConceptEntity;
      case LanguageConceptSwitch.EntityOperationHolder:
        return myConceptEntityOperationHolder;
      case LanguageConceptSwitch.EntityRef:
        return myConceptEntityRef;
      case LanguageConceptSwitch.Field:
        return myConceptField;
      case LanguageConceptSwitch.FieldAnnotationHolder:
        return myConceptFieldAnnotationHolder;
      case LanguageConceptSwitch.FieldTypeHolder:
        return myConceptFieldTypeHolder;
      case LanguageConceptSwitch.NatsServer:
        return myConceptNatsServer;
      case LanguageConceptSwitch.Relation:
        return myConceptRelation;
      case LanguageConceptSwitch.RelationOperationHolder:
        return myConceptRelationOperationHolder;
      case LanguageConceptSwitch.RelationRef:
        return myConceptRelationRef;
      case LanguageConceptSwitch.SqlSchem:
        return myConceptSqlSchem;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationEntityOperation, myEnumerationFieldAnnotation, myEnumerationFieldType, myEnumerationRelationOperation);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForEntity() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UserManagement", "Entity", 0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac7eL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:a3a366a2-da30-48fe-b644-04a6d92b06a4(UserManagement.structure)/7669448123827596414");
    b.version(3);
    b.associate("server", 0x6a6f5a6f243a4ec9L).target(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac21L).optional(true).origin("7669448123830914761").done();
    b.aggregate("fields", 0x6a6f5a6f2407ac84L).target(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac68L).optional(false).ordered(true).multiple(true).origin("7669448123827596420").done();
    b.aggregate("operations", 0x6a6f5a6f2407ac86L).target(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac89L).optional(false).ordered(true).multiple(true).origin("7669448123827596422").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEntityOperationHolder() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UserManagement", "EntityOperationHolder", 0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac89L);
    b.class_(false, false, false);
    b.origin("r:a3a366a2-da30-48fe-b644-04a6d92b06a4(UserManagement.structure)/7669448123827596425");
    b.version(3);
    b.property("entityOperation", 0x6a6f5a6f2407ac8bL).type(MetaIdFactory.dataTypeId(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac57L)).origin("7669448123827596427").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEntityRef() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UserManagement", "EntityRef", 0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f243a4ec1L);
    b.class_(false, false, false);
    b.origin("r:a3a366a2-da30-48fe-b644-04a6d92b06a4(UserManagement.structure)/7669448123830914753");
    b.version(3);
    b.associate("entity", 0x6a6f5a6f243a4ec2L).target(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac7eL).optional(false).origin("7669448123830914754").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForField() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UserManagement", "Field", 0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac68L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:a3a366a2-da30-48fe-b644-04a6d92b06a4(UserManagement.structure)/7669448123827596392");
    b.version(3);
    b.associate("targetEntity", 0x6a6f5a6f242a92c6L).target(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac7eL).optional(true).origin("7669448123829883590").done();
    b.aggregate("anotations", 0x6a6f5a6f2407ac76L).target(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac73L).optional(true).ordered(true).multiple(true).origin("7669448123827596406").done();
    b.aggregate("type", 0x6a6f5a6f240f1046L).target(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac7aL).optional(false).ordered(true).multiple(false).origin("7669448123828080710").done();
    b.alias("f");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFieldAnnotationHolder() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UserManagement", "FieldAnnotationHolder", 0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac73L);
    b.class_(false, false, false);
    b.origin("r:a3a366a2-da30-48fe-b644-04a6d92b06a4(UserManagement.structure)/7669448123827596403");
    b.version(3);
    b.property("annotation", 0x6a6f5a6f2407ac74L).type(MetaIdFactory.dataTypeId(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac46L)).origin("7669448123827596404").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFieldTypeHolder() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UserManagement", "FieldTypeHolder", 0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac7aL);
    b.class_(false, false, false);
    b.origin("r:a3a366a2-da30-48fe-b644-04a6d92b06a4(UserManagement.structure)/7669448123827596410");
    b.version(3);
    b.property("fieldType", 0x6a6f5a6f2407ac7bL).type(MetaIdFactory.dataTypeId(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac38L)).origin("7669448123827596411").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForNatsServer() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UserManagement", "NatsServer", 0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac21L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:a3a366a2-da30-48fe-b644-04a6d92b06a4(UserManagement.structure)/7669448123827596321");
    b.version(3);
    b.property("tenentID", 0x6a6f5a6f2407ac27L).type(PrimitiveTypeId.STRING).origin("7669448123827596327").done();
    b.property("defaultNatsUrl", 0x6a6f5a6f2407ac29L).type(PrimitiveTypeId.STRING).origin("7669448123827596329").done();
    b.property("subjectPrefix", 0x6a6f5a6f2407ac35L).type(PrimitiveTypeId.STRING).origin("7669448123827596341").done();
    b.property("dbSchema", 0x6a6f5a6f2407ac36L).type(PrimitiveTypeId.STRING).origin("7669448123827596342").done();
    b.aggregate("entities", 0x6a6f5a6f2407acacL).target(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f243a4ec1L).optional(false).ordered(true).multiple(true).origin("7669448123827596460").done();
    b.aggregate("relations", 0x6a6f5a6f2407acaeL).target(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f243a4ec5L).optional(true).ordered(true).multiple(true).origin("7669448123827596462").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRelation() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UserManagement", "Relation", 0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac8fL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:a3a366a2-da30-48fe-b644-04a6d92b06a4(UserManagement.structure)/7669448123827596431");
    b.version(3);
    b.associate("from", 0x6a6f5a6f2407ac95L).target(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac7eL).optional(false).origin("7669448123827596437").done();
    b.associate("to", 0x6a6f5a6f2407ac97L).target(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac7eL).optional(false).origin("7669448123827596439").done();
    b.associate("server", 0x6a6f5a6f243a4eccL).target(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac21L).optional(true).origin("7669448123830914764").done();
    b.aggregate("operations", 0x6a6f5a6f2407ac9aL).target(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac9cL).optional(false).ordered(true).multiple(true).origin("7669448123827596442").done();
    b.aggregate("extraFields", 0x6a6f5a6f2407aca2L).target(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac68L).optional(true).ordered(true).multiple(true).origin("7669448123827596450").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRelationOperationHolder() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UserManagement", "RelationOperationHolder", 0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac9cL);
    b.class_(false, false, false);
    b.origin("r:a3a366a2-da30-48fe-b644-04a6d92b06a4(UserManagement.structure)/7669448123827596444");
    b.version(3);
    b.property("relationOperation", 0x6a6f5a6f2407ac9eL).type(MetaIdFactory.dataTypeId(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac61L)).origin("7669448123827596446").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRelationRef() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UserManagement", "RelationRef", 0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f243a4ec5L);
    b.class_(false, false, false);
    b.origin("r:a3a366a2-da30-48fe-b644-04a6d92b06a4(UserManagement.structure)/7669448123830914757");
    b.version(3);
    b.associate("relation", 0x6a6f5a6f243a4ec6L).target(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac8fL).optional(false).origin("7669448123830914758").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSqlSchem() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UserManagement", "SqlSchem", 0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f243a4eceL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:a3a366a2-da30-48fe-b644-04a6d92b06a4(UserManagement.structure)/7669448123830914766");
    b.version(3);
    b.property("dbSchema", 0x6a6f5a6f243a4ed2L).type(PrimitiveTypeId.STRING).origin("7669448123830914770").done();
    b.aggregate("entityrefs", 0x6a6f5a6f243a4ed6L).target(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f243a4ec1L).optional(true).ordered(true).multiple(true).origin("7669448123830914774").done();
    b.aggregate("relations", 0x6a6f5a6f243a4ed7L).target(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f243a4ec5L).optional(true).ordered(true).multiple(true).origin("7669448123830914775").done();
    return b.create();
  }
}
