package UserManagement.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class FieldAnnotationHolder_Constraints extends BaseConstraintsDescriptor {
  /*package*/ FieldAnnotationHolder_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.FieldAnnotationHolder$3e, initContext);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept FieldAnnotationHolder$3e = MetaAdapterFactory.getConcept(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac73L, "UserManagement.structure.FieldAnnotationHolder");
  }
}
