package UserManagement.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBehaviorAspectDescriptor;
import jetbrains.mps.core.aspects.behaviour.api.BHDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public final class BehaviorAspectDescriptor extends BaseBehaviorAspectDescriptor {
  private final BHDescriptor myField__BehaviorDescriptor = new Field__BehaviorDescriptor();
  private final BHDescriptor myEntity__BehaviorDescriptor = new Entity__BehaviorDescriptor();
  private final BHDescriptor myEntityOperationHolder__BehaviorDescriptor = new EntityOperationHolder__BehaviorDescriptor();
  private final BHDescriptor myRelation__BehaviorDescriptor = new Relation__BehaviorDescriptor();
  private final BHDescriptor myRelationOperationHolder__BehaviorDescriptor = new RelationOperationHolder__BehaviorDescriptor();

  public BehaviorAspectDescriptor() {
  }

  @Nullable
  public BHDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return myEntity__BehaviorDescriptor;
      case 1:
        return myEntityOperationHolder__BehaviorDescriptor;
      case 2:
        return myField__BehaviorDescriptor;
      case 3:
        return myRelation__BehaviorDescriptor;
      case 4:
        return myRelationOperationHolder__BehaviorDescriptor;
      default:
    }
    return null;
  }
  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac7eL), MetaIdFactory.conceptId(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac89L), MetaIdFactory.conceptId(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac68L), MetaIdFactory.conceptId(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac8fL), MetaIdFactory.conceptId(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac9cL)).seal();
}
