package UserManagement.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.behaviour.api.SMethod;
import jetbrains.mps.core.aspects.behaviour.SMethodBuilder;
import jetbrains.mps.core.aspects.behaviour.SJavaCompoundTypeImpl;
import jetbrains.mps.core.aspects.behaviour.AccessPrivileges;
import org.jetbrains.mps.openapi.model.SNode;
import java.util.List;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SEnumOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.core.aspects.behaviour.api.SConstructor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.core.aspects.behaviour.api.BHMethodNotFoundException;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SProperty;

public final class Entity__BehaviorDescriptor extends BaseBHDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac7eL, "UserManagement.structure.Entity");

  public static final SMethod<String> capitalizeString_id2H11bzbgsj$ = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("capitalizeString").modifiers(1, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(3116777608847672548L).languageId(0x91c4fb1f5af2c6d7L, 0x2fbdea0625174783L).build2(SMethodBuilder.createJavaParameter(String.class, ""));
  public static final SMethod<String> apppendTypeIfEmailPass_id24dYXnugYNM = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("apppendTypeIfEmailPass").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(2381836673924459762L).languageId(0x91c4fb1f5af2c6d7L, 0x2fbdea0625174783L).build2();
  public static final SMethod<SNode> primaryKeyField_id6DJmAW$csS2 = new SMethodBuilder<SNode>(new SJavaCompoundTypeImpl((Class<SNode>) ((Class) Object.class))).name("primaryKeyField").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(7669448123830357506L).languageId(0x91c4fb1f5af2c6d7L, 0x2fbdea0625174783L).build2();
  public static final SMethod<String> creteValidation_id6DJmAW$hYDa = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("creteValidation").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(7669448123831806538L).languageId(0x91c4fb1f5af2c6d7L, 0x2fbdea0625174783L).build2();
  public static final SMethod<String> schemaTableName_id6DJmAW$eABX = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("schemaTableName").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(7669448123830921725L).languageId(0x91c4fb1f5af2c6d7L, 0x2fbdea0625174783L).build2(SMethodBuilder.createJavaParameter(String.class, ""));
  public static final SMethod<String> tableName_id6DJmAW$e3L$ = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("tableName").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(7669448123830778980L).languageId(0x91c4fb1f5af2c6d7L, 0x2fbdea0625174783L).build2();
  public static final SMethod<String> toLoverCaseFirst_id6LRrEr4Y7HY = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("toLoverCaseFirst").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(7815837340873030526L).languageId(0x91c4fb1f5af2c6d7L, 0x2fbdea0625174783L).build2();
  public static final SMethod<String> createValidation_id6DJmAW$cIRR = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("createValidation").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(7669448123830431223L).languageId(0x91c4fb1f5af2c6d7L, 0x2fbdea0625174783L).build2();
  public static final SMethod<Boolean> needWorkerPool_id2H11bzbGg3I = new SMethodBuilder<Boolean>(new SJavaCompoundTypeImpl(Boolean.TYPE)).name("needWorkerPool").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(3116777608854962414L).languageId(0x91c4fb1f5af2c6d7L, 0x2fbdea0625174783L).build2();

  private static final List<SMethod<?>> BH_METHODS = Arrays.<SMethod<?>>asList(capitalizeString_id2H11bzbgsj$, apppendTypeIfEmailPass_id24dYXnugYNM, primaryKeyField_id6DJmAW$csS2, creteValidation_id6DJmAW$hYDa, schemaTableName_id6DJmAW$eABX, tableName_id6DJmAW$e3L$, toLoverCaseFirst_id6LRrEr4Y7HY, createValidation_id6DJmAW$cIRR, needWorkerPool_id2H11bzbGg3I);

  private static void ___init___(@NotNull SNode __thisNode__) {
  }

  /*package*/ static String capitalizeString_id2H11bzbgsj$(@NotNull SAbstractConcept __thisConcept__, String in) {
    return (in.charAt(0) + "").toUpperCase() + in.subSequence(1, in.length());
  }
  /*package*/ static String apppendTypeIfEmailPass_id24dYXnugYNM(@NotNull SNode __thisNode__) {
    String returns = "";

    if (ListSequence.fromList(SLinkOperations.getChildren(__thisNode__, LINKS.fields$Rrud)).any((it) -> SEnumOperations.getMemberName0(SPropertyOperations.getEnum(SLinkOperations.getTarget(it, LINKS.type$KBb7), PROPS.fieldType$RkpN)).equals("password") || SEnumOperations.getMemberName0(SPropertyOperations.getEnum(SLinkOperations.getTarget(it, LINKS.type$KBb7), PROPS.fieldType$RkpN)).equals("email"))) {
      returns = "\"dev.azure.com/Motadata/NextGen/motadata-go-sdk/core/types\"\n";
    }

    return returns;
  }
  /*package*/ static SNode primaryKeyField_id6DJmAW$csS2(@NotNull SNode __thisNode__) {
    for (SNode f : ListSequence.fromList(SLinkOperations.getChildren(__thisNode__, LINKS.fields$Rrud))) {
      if ((boolean) Field__BehaviorDescriptor.hasAnotation_id6DJmAW$hoUl.invoke(f, "primaryKey")) {
        return f;
      }
    }
    return null;
  }
  /*package*/ static String creteValidation_id6DJmAW$hYDa(@NotNull SNode __thisNode__) {
    String result = "";
    int i = 0;


    for (SNode field : ListSequence.fromList(SLinkOperations.getChildren(__thisNode__, LINKS.fields$Rrud))) {
      if ((boolean) Field__BehaviorDescriptor.hasAnotation_id6DJmAW$hoUl.invoke(field, "required") && !((boolean) Field__BehaviorDescriptor.hasAnotation_id6DJmAW$hoUl.invoke(field, "auto")) && !((boolean) Field__BehaviorDescriptor.hasAnotation_id6DJmAW$hoUl.invoke(field, "primaryKey"))) {
        if (i > 0) {
          result = result + " || ";
        }
        result = result + "event." + SPropertyOperations.getString(field, PROPS.name$MnvL) + " == \"\"";
        i = i + 1;
      }
    }
    return result;
  }
  /*package*/ static String schemaTableName_id6DJmAW$eABX(@NotNull SNode __thisNode__, String schema) {
    return schema + "." + Entity__BehaviorDescriptor.tableName_id6DJmAW$e3L$.invoke(__thisNode__);
  }
  /*package*/ static String tableName_id6DJmAW$e3L$(@NotNull SNode __thisNode__) {
    return SPropertyOperations.getString(__thisNode__, PROPS.name$MnvL).toLowerCase();
  }
  /*package*/ static String toLoverCaseFirst_id6LRrEr4Y7HY(@NotNull SNode __thisNode__) {
    String s = SPropertyOperations.getString(__thisNode__, PROPS.name$MnvL);
    return (s.charAt(0) + "").toLowerCase() + s.subSequence(1, s.length());
  }
  /*package*/ static String createValidation_id6DJmAW$cIRR(@NotNull SNode __thisNode__) {
    String result = "";
    int i = 0;
    for (SNode f : ListSequence.fromList(SLinkOperations.getChildren(__thisNode__, LINKS.fields$Rrud))) {
      if (ListSequence.fromList(SLinkOperations.getChildren(f, LINKS.anotations$R8V0)).any((it) -> {
        String anot = SPropertyOperations.getEnum(it, PROPS.annotation$RdBN).getPresentation();
        if (anot.equals("required") && !(anot.equals("auto")) && !(anot.equals("primaryKey"))) {
          return true;
        }
        return false;
      })) {
        if (i > 0) {
          result = result + " || ";
        }
        result = result + "event." + SPropertyOperations.getString(f, PROPS.name$MnvL) + " == \"\"";
        i = i + 1;
      }
    }
    return result;
  }
  /*package*/ static boolean needWorkerPool_id2H11bzbGg3I(@NotNull SNode __thisNode__) {
    return ListSequence.fromList(SLinkOperations.getChildren(__thisNode__, LINKS.preHooksNamed$xIX)).any((hooksHolder) -> ListSequence.fromList(SLinkOperations.getChildren(hooksHolder, LINKS.Hooks$E6NN)).any((h) -> SPropertyOperations.getBoolean(h, PROPS.isAsync$Nysa))) || ListSequence.fromList(SLinkOperations.getChildren(__thisNode__, LINKS.postHooksNamed$xXY)).any((hooksHolder) -> ListSequence.fromList(SLinkOperations.getChildren(hooksHolder, LINKS.Hooks$E6NN)).any((h) -> SPropertyOperations.getBoolean(h, PROPS.isAsync$Nysa)));
  }

  /*package*/ Entity__BehaviorDescriptor() {
  }

  @Override
  protected void initNode(@NotNull SNode node, @NotNull SConstructor constructor, @Nullable Object[] parameters) {
    ___init___(node);
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SNode node, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 1:
        return (T) ((String) apppendTypeIfEmailPass_id24dYXnugYNM(node));
      case 2:
        return (T) ((SNode) primaryKeyField_id6DJmAW$csS2(node));
      case 3:
        return (T) ((String) creteValidation_id6DJmAW$hYDa(node));
      case 4:
        return (T) ((String) schemaTableName_id6DJmAW$eABX(node, (String) parameters[0]));
      case 5:
        return (T) ((String) tableName_id6DJmAW$e3L$(node));
      case 6:
        return (T) ((String) toLoverCaseFirst_id6LRrEr4Y7HY(node));
      case 7:
        return (T) ((String) createValidation_id6DJmAW$cIRR(node));
      case 8:
        return (T) ((Boolean) needWorkerPool_id2H11bzbGg3I(node));
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SAbstractConcept concept, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 0:
        return (T) ((String) capitalizeString_id2H11bzbgsj$(concept, (String) parameters[0]));
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @NotNull
  @Override
  public List<SMethod<?>> getDeclaredMethods() {
    return BH_METHODS;
  }

  @NotNull
  @Override
  public SAbstractConcept getConcept() {
    return CONCEPT;
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink fields$Rrud = MetaAdapterFactory.getContainmentLink(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac7eL, 0x6a6f5a6f2407ac84L, "fields");
    /*package*/ static final SContainmentLink type$KBb7 = MetaAdapterFactory.getContainmentLink(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac68L, 0x6a6f5a6f240f1046L, "type");
    /*package*/ static final SContainmentLink anotations$R8V0 = MetaAdapterFactory.getContainmentLink(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac68L, 0x6a6f5a6f2407ac76L, "anotations");
    /*package*/ static final SContainmentLink preHooksNamed$xIX = MetaAdapterFactory.getContainmentLink(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac7eL, 0x2b4104b8cb107decL, "preHooksNamed");
    /*package*/ static final SContainmentLink Hooks$E6NN = MetaAdapterFactory.getContainmentLink(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x2b4104b8cb107de9L, 0x2b4104b8cb107deaL, "Hooks");
    /*package*/ static final SContainmentLink postHooksNamed$xXY = MetaAdapterFactory.getContainmentLink(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac7eL, 0x2b4104b8cb107dedL, "postHooksNamed");
  }

  private static final class PROPS {
    /*package*/ static final SProperty fieldType$RkpN = MetaAdapterFactory.getProperty(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac7aL, 0x6a6f5a6f2407ac7bL, "fieldType");
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
    /*package*/ static final SProperty annotation$RdBN = MetaAdapterFactory.getProperty(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac73L, 0x6a6f5a6f2407ac74L, "annotation");
    /*package*/ static final SProperty isAsync$Nysa = MetaAdapterFactory.getProperty(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x2b4104b8cb107debL, 0x2b4104b8cb8c2ff7L, "isAsync");
  }
}
