package UserManagement.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.behaviour.api.SMethod;
import jetbrains.mps.core.aspects.behaviour.SMethodBuilder;
import jetbrains.mps.core.aspects.behaviour.SJavaCompoundTypeImpl;
import jetbrains.mps.core.aspects.behaviour.AccessPrivileges;
import java.util.List;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SEnumOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.core.aspects.behaviour.api.SConstructor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.core.aspects.behaviour.api.BHMethodNotFoundException;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public final class Field__BehaviorDescriptor extends BaseBHDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac68L, "UserManagement.structure.Field");

  public static final SMethod<Boolean> hasAnotation_id6DJmAW$hoUl = new SMethodBuilder<Boolean>(new SJavaCompoundTypeImpl(Boolean.TYPE)).name("hasAnotation").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(7669448123831651989L).languageId(0x91c4fb1f5af2c6d7L, 0x2fbdea0625174783L).build2(SMethodBuilder.createJavaParameter(String.class, ""));
  public static final SMethod<String> sqlType_id6DJmAW$aWx9 = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("sqlType").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(7669448123829962825L).languageId(0x91c4fb1f5af2c6d7L, 0x2fbdea0625174783L).build2();
  public static final SMethod<String> goType_id6DJmAW$aE7I = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("goType").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(7669448123829887470L).languageId(0x91c4fb1f5af2c6d7L, 0x2fbdea0625174783L).build2();
  public static final SMethod<String> jsonTag_id6DJmAW$b545 = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("jsonTag").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(7669448123829997829L).languageId(0x91c4fb1f5af2c6d7L, 0x2fbdea0625174783L).build2();
  public static final SMethod<String> jsonName_id6DJmAW$7ald = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("jsonName").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(7669448123828970829L).languageId(0x91c4fb1f5af2c6d7L, 0x2fbdea0625174783L).build2();
  public static final SMethod<String> fkConstrainst_id6DJmAW$cjVl = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("fkConstrainst").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(7669448123830320853L).languageId(0x91c4fb1f5af2c6d7L, 0x2fbdea0625174783L).build2();
  public static final SMethod<String> dbName_id6DJmAW$7pGu = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("dbName").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(7669448123829033758L).languageId(0x91c4fb1f5af2c6d7L, 0x2fbdea0625174783L).build2();

  private static final List<SMethod<?>> BH_METHODS = Arrays.<SMethod<?>>asList(hasAnotation_id6DJmAW$hoUl, sqlType_id6DJmAW$aWx9, goType_id6DJmAW$aE7I, jsonTag_id6DJmAW$b545, jsonName_id6DJmAW$7ald, fkConstrainst_id6DJmAW$cjVl, dbName_id6DJmAW$7pGu);

  private static void ___init___(@NotNull SNode __thisNode__) {
  }

  /*package*/ static boolean hasAnotation_id6DJmAW$hoUl(@NotNull SNode __thisNode__, String anotationName) {
    for (SNode an : ListSequence.fromList(SLinkOperations.getChildren(__thisNode__, LINKS.anotations$R8V0))) {
      if (SEnumOperations.getMemberName0(SPropertyOperations.getEnum(an, PROPS.annotation$RdBN)).equals(anotationName)) {
        return true;
      }
    }
    return false;
  }
  /*package*/ static String sqlType_id6DJmAW$aWx9(@NotNull SNode __thisNode__) {
    String ft = SEnumOperations.getMemberName0(SPropertyOperations.getEnum(SLinkOperations.getTarget(__thisNode__, LINKS.type$KBb7), PROPS.fieldType$RkpN));
    if (ft.equals("uuid")) {
      return "UUID";
    }
    if (ft.equals("string")) {
      return "VARCHAR(255)";
    }
    if (ft.equals("text")) {
      return "TEXT";
    }
    if (ft.equals("int")) {
      return "BIGINT";
    }
    if (ft.equals("bool")) {
      return "BOOLEAN";
    }
    if (ft.equals("time")) {
      return "TIMESTAMPTZ";
    }
    if (ft.equals("json")) {
      return "JSONB";
    }
    if (ft.equals("email")) {
      return "VARCHAR(255)";
    }
    if (ft.equals("password")) {
      return "VARCHAR(255)";
    }
    if (ft.equals("entityRef")) {
      return "UUID";
    }
    return "TEXT";
  }
  /*package*/ static String goType_id6DJmAW$aE7I(@NotNull SNode __thisNode__) {
    String ft = SEnumOperations.getMemberName0(SPropertyOperations.getEnum(SLinkOperations.getTarget(__thisNode__, LINKS.type$KBb7), PROPS.fieldType$RkpN));
    if (ft.equals("uuid")) {
      return "string";
    }
    if (ft.equals("string")) {
      return "string";
    }
    if (ft.equals("text")) {
      return "string";
    }
    if (ft.equals("int")) {
      return "int64";
    }
    if (ft.equals("bool")) {
      return "bool";
    }
    if (ft.equals("time")) {
      return "time.Time";
    }
    if (ft.equals("json")) {
      return "json.RawMessage";
    }
    if (ft.equals("email")) {
      return "string";
    }
    if (ft.equals("password")) {
      return "string";
    }
    if (ft.equals("entityRef")) {
      return "string";
    }
    return "interface{}";
  }
  /*package*/ static String jsonTag_id6DJmAW$b545(@NotNull SNode __thisNode__) {
    if (SPropertyOperations.getEnum(SLinkOperations.getTarget(__thisNode__, LINKS.type$KBb7), PROPS.fieldType$RkpN).getPresentation().equals("password")) {
      return "-";
    }
    return Field__BehaviorDescriptor.jsonName_id6DJmAW$7ald.invoke(__thisNode__);
  }
  /*package*/ static String jsonName_id6DJmAW$7ald(@NotNull SNode __thisNode__) {
    String name = SPropertyOperations.getString(__thisNode__, PROPS.name$MnvL);
    StringBuilder sb = new StringBuilder();
    for (int i = 0; i < name.length(); i++) {
      char ch = name.charAt(i);
      if (ch >= 'A' && ch <= 'Z' && i > 0) {
        sb.append('_');
        sb.append(Character.toLowerCase(ch));
      } else {
        sb.append(Character.toLowerCase(ch));
      }
    }
    return sb.toString();
  }
  /*package*/ static String fkConstrainst_id6DJmAW$cjVl(@NotNull SNode __thisNode__) {
    if (SPropertyOperations.getEnum(SLinkOperations.getTarget(__thisNode__, LINKS.type$KBb7), PROPS.fieldType$RkpN).getPresentation().equals("entityRef") && SLinkOperations.getTarget(__thisNode__, LINKS.targetEntity$5$qj) != null) {
      return "REFERENCES " + Entity__BehaviorDescriptor.tableName_id6DJmAW$e3L$.invoke(SLinkOperations.getTarget(__thisNode__, LINKS.targetEntity$5$qj)) + "(id)";
    }
    return "";
  }
  /*package*/ static String dbName_id6DJmAW$7pGu(@NotNull SNode __thisNode__) {
    return ((String) Field__BehaviorDescriptor.jsonName_id6DJmAW$7ald.invoke(__thisNode__));
  }

  /*package*/ Field__BehaviorDescriptor() {
  }

  @Override
  protected void initNode(@NotNull SNode node, @NotNull SConstructor constructor, @Nullable Object[] parameters) {
    ___init___(node);
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SNode node, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 0:
        return (T) ((Boolean) hasAnotation_id6DJmAW$hoUl(node, (String) parameters[0]));
      case 1:
        return (T) ((String) sqlType_id6DJmAW$aWx9(node));
      case 2:
        return (T) ((String) goType_id6DJmAW$aE7I(node));
      case 3:
        return (T) ((String) jsonTag_id6DJmAW$b545(node));
      case 4:
        return (T) ((String) jsonName_id6DJmAW$7ald(node));
      case 5:
        return (T) ((String) fkConstrainst_id6DJmAW$cjVl(node));
      case 6:
        return (T) ((String) dbName_id6DJmAW$7pGu(node));
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SAbstractConcept concept, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @NotNull
  @Override
  public List<SMethod<?>> getDeclaredMethods() {
    return BH_METHODS;
  }

  @NotNull
  @Override
  public SAbstractConcept getConcept() {
    return CONCEPT;
  }

  private static final class PROPS {
    /*package*/ static final SProperty annotation$RdBN = MetaAdapterFactory.getProperty(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac73L, 0x6a6f5a6f2407ac74L, "annotation");
    /*package*/ static final SProperty fieldType$RkpN = MetaAdapterFactory.getProperty(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac7aL, 0x6a6f5a6f2407ac7bL, "fieldType");
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink anotations$R8V0 = MetaAdapterFactory.getContainmentLink(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac68L, 0x6a6f5a6f2407ac76L, "anotations");
    /*package*/ static final SContainmentLink type$KBb7 = MetaAdapterFactory.getContainmentLink(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac68L, 0x6a6f5a6f240f1046L, "type");
    /*package*/ static final SReferenceLink targetEntity$5$qj = MetaAdapterFactory.getReferenceLink(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac68L, 0x6a6f5a6f242a92c6L, "targetEntity");
  }
}
