package UserManagement.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.behaviour.api.SMethod;
import jetbrains.mps.core.aspects.behaviour.SMethodBuilder;
import jetbrains.mps.core.aspects.behaviour.SJavaCompoundTypeImpl;
import jetbrains.mps.core.aspects.behaviour.AccessPrivileges;
import java.util.List;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.core.aspects.behaviour.api.SConstructor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.core.aspects.behaviour.api.BHMethodNotFoundException;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import org.jetbrains.mps.openapi.language.SConcept;
import org.jetbrains.mps.openapi.language.SProperty;

public final class FieldAnnotationHolder__BehaviorDescriptor extends BaseBHDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac73L, "UserManagement.structure.FieldAnnotationHolder");

  public static final SMethod<String> getSqlAnotationMeaning_id2hFdsTnGhoh = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("getSqlAnotationMeaning").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(2624250368224204305L).languageId(0x91c4fb1f5af2c6d7L, 0x2fbdea0625174783L).build2();

  private static final List<SMethod<?>> BH_METHODS = Arrays.<SMethod<?>>asList(getSqlAnotationMeaning_id2hFdsTnGhoh);

  private static void ___init___(@NotNull SNode __thisNode__) {
  }

  /*package*/ static String getSqlAnotationMeaning_id2hFdsTnGhoh(@NotNull SNode __thisNode__) {
    switch (enumSwitchIndex.indexNullable(SPropertyOperations.getEnum(__thisNode__, PROPS.annotation$RdBN))) {
      case 0:
        return Field__BehaviorDescriptor.getDefault_id2hFdsTnFAcg.invoke(SNodeOperations.getNodeAncestor(__thisNode__, CONCEPTS.Field$Sp, false, false));
      case 1:
      case 2:
      case 3:
      case 4:
        return "";
      case 5:
        return "PRIMARY KEY";
      case 6:
        return "NOT NULL";
      case 7:
        return "UNIQUE";
      default:
        return null;
    }
  }

  /*package*/ FieldAnnotationHolder__BehaviorDescriptor() {
  }

  @Override
  protected void initNode(@NotNull SNode node, @NotNull SConstructor constructor, @Nullable Object[] parameters) {
    ___init___(node);
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SNode node, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 0:
        return (T) ((String) getSqlAnotationMeaning_id2hFdsTnGhoh(node));
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SAbstractConcept concept, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @NotNull
  @Override
  public List<SMethod<?>> getDeclaredMethods() {
    return BH_METHODS;
  }

  @NotNull
  @Override
  public SAbstractConcept getConcept() {
    return CONCEPT;
  }
  private static final EnumerationLiteralsIndex enumSwitchIndex = EnumerationLiteralsIndex.build(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac46L, 0x6a6f5a6f2407ac54L, 0x210dfbd5de60726eL, 0x6a6f5a6f2407ac52L, 0x6a6f5a6f2407ac50L, 0x6a6f5a6f2407ac4cL, 0x6a6f5a6f2407ac47L, 0x6a6f5a6f2407ac49L, 0x6a6f5a6f2407ac4eL);

  private static final class CONCEPTS {
    /*package*/ static final SConcept Field$Sp = MetaAdapterFactory.getConcept(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac68L, "UserManagement.structure.Field");
  }

  private static final class PROPS {
    /*package*/ static final SProperty annotation$RdBN = MetaAdapterFactory.getProperty(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac73L, 0x6a6f5a6f2407ac74L, "annotation");
  }
}
