package UserManagement.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.behaviour.api.SMethod;
import jetbrains.mps.core.aspects.behaviour.SMethodBuilder;
import jetbrains.mps.core.aspects.behaviour.SJavaCompoundTypeImpl;
import jetbrains.mps.core.aspects.behaviour.AccessPrivileges;
import org.jetbrains.mps.openapi.model.SNode;
import java.util.List;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.core.aspects.behaviour.api.SConstructor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.core.aspects.behaviour.api.BHMethodNotFoundException;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SProperty;

public final class HookTypeHooksHolder__BehaviorDescriptor extends BaseBHDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x2b4104b8cb107de9L, "UserManagement.structure.HookTypeHooksHolder");

  public static final SMethod<String[]> getHookNames_id2H11bzbam1c = new SMethodBuilder<String[]>(new SJavaCompoundTypeImpl(String[].class)).name("getHookNames").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(3116777608846073932L).languageId(0x91c4fb1f5af2c6d7L, 0x2fbdea0625174783L).build2(SMethodBuilder.createJavaParameter(String.class, ""));
  public static final SMethod<Iterable<SNode>> getHooksSorted_id2H11bzboFUZ = new SMethodBuilder<Iterable<SNode>>(new SJavaCompoundTypeImpl((Class<Iterable<SNode>>) ((Class) Object.class))).name("getHooksSorted").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(3116777608849833663L).languageId(0x91c4fb1f5af2c6d7L, 0x2fbdea0625174783L).build2();

  private static final List<SMethod<?>> BH_METHODS = Arrays.<SMethod<?>>asList(getHookNames_id2H11bzbam1c, getHooksSorted_id2H11bzboFUZ);

  private static void ___init___(@NotNull SNode __thisNode__) {
  }

  /*package*/ static String[] getHookNames_id2H11bzbam1c(@NotNull SNode __thisNode__, final String hook) {
    Iterable<String> names = ListSequence.fromList(SLinkOperations.getChildren(__thisNode__, LINKS.Hooks$E6NN)).where((it) -> SPropertyOperations.getString(it, PROPS.name$MnvL).equals(hook)).select((it) -> SPropertyOperations.getString(it, PROPS.name$MnvL));
    return Sequence.fromIterable(names).toGenericArray(String.class);
  }
  /*package*/ static Iterable<SNode> getHooksSorted_id2H11bzboFUZ(@NotNull SNode __thisNode__) {
    return ListSequence.fromList(SLinkOperations.getChildren(__thisNode__, LINKS.Hooks$E6NN)).sort((it) -> SPropertyOperations.getInteger(it, PROPS.priority$3U5o), false);
  }

  /*package*/ HookTypeHooksHolder__BehaviorDescriptor() {
  }

  @Override
  protected void initNode(@NotNull SNode node, @NotNull SConstructor constructor, @Nullable Object[] parameters) {
    ___init___(node);
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SNode node, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 0:
        return (T) ((String[]) getHookNames_id2H11bzbam1c(node, (String) parameters[0]));
      case 1:
        return (T) ((Iterable<SNode>) getHooksSorted_id2H11bzboFUZ(node));
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SAbstractConcept concept, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @NotNull
  @Override
  public List<SMethod<?>> getDeclaredMethods() {
    return BH_METHODS;
  }

  @NotNull
  @Override
  public SAbstractConcept getConcept() {
    return CONCEPT;
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink Hooks$E6NN = MetaAdapterFactory.getContainmentLink(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x2b4104b8cb107de9L, 0x2b4104b8cb107deaL, "Hooks");
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
    /*package*/ static final SProperty priority$3U5o = MetaAdapterFactory.getProperty(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x2b4104b8cb107debL, 0x2b4104b8cb59e86eL, "priority");
  }
}
