package UserManagement.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import UserManagement.behavior.Entity__BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import UserManagement.behavior.Field__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SEnumOperations;
import UserManagement.behavior.EntityOperationHolder__BehaviorDescriptor;
import jetbrains.mps.internal.collections.runtime.Sequence;
import UserManagement.behavior.HookTypeHooksHolder__BehaviorDescriptor;
import UserManagement.behavior.Hook__BehaviorDescriptor;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class Entity_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);

    String name = SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.name$MnvL);
    String nameLower = name.toLowerCase();
    String pkField = SPropertyOperations.getString(Entity__BehaviorDescriptor.primaryKeyField_id6DJmAW$csS2.invoke(ctx.getPrimaryInput()), PROPS.name$MnvL);

    tgs.append("package main");
    tgs.newLine();
    tgs.newLine();
    tgs.append("import (");
    tgs.newLine();
    tgs.append(" \"context\"");
    tgs.newLine();
    tgs.append(" \"encoding/json\"");
    tgs.newLine();
    tgs.append(" \"fmt\"");
    tgs.newLine();
    tgs.append(" \"time\"");
    tgs.newLine();
    tgs.newLine();
    tgs.append(" \"github.com/nats-io/nats.go\"");
    tgs.newLine();
    tgs.newLine();
    tgs.append(" \"dev.azure.com/Motadata/NextGen/motadata-go-sdk/events\"");
    tgs.newLine();
    tgs.append(" \"dev.azure.com/Motadata/NextGen/motadata-go-sdk/events/core\"");
    tgs.newLine();
    tgs.append(" \"dev.azure.com/Motadata/NextGen/motadata-go-sdk/otel/tracer\"");
    tgs.newLine();
    tgs.append(" \"dev.azure.com/Motadata/NextGen/motadata-go-sdk/otel/logger\"");
    tgs.newLine();
    tgs.append(((boolean) Entity__BehaviorDescriptor.needWorkerPool_id2H11bzbGg3I.invoke(ctx.getPrimaryInput()) ? "\"dev.azure.com/Motadata/NextGen/motadata-go-sdk/core/pool/workerpool\"" : ""));
    tgs.newLine();
    tgs.append(")");
    tgs.newLine();
    tgs.newLine();

    tgs.append("type ");
    tgs.append(name);
    tgs.append(" struct {");
    tgs.newLine();

    for (SNode f : ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.fields$Rrud))) {
      tgs.append(" ");
      tgs.append(Field__BehaviorDescriptor.capitalize_id5Lqw_By60m2.invoke(f));
      tgs.append(" ");
      tgs.append(Field__BehaviorDescriptor.goType_id6DJmAW$aE7I.invoke(f));
      tgs.append(" `json:\"");
      tgs.append(Field__BehaviorDescriptor.jsonName_id6DJmAW$7ald.invoke(f));
      tgs.append("\" db:\"");
      tgs.append(Field__BehaviorDescriptor.dbName_id6DJmAW$7pGu.invoke(f));
      tgs.append("\"`");
      tgs.newLine();
    }
    tgs.append("}");
    tgs.newLine();
    tgs.newLine();

    for (SNode op : ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.operations$RrWf))) {
      if (SEnumOperations.getMemberName0(SPropertyOperations.getEnum(op, PROPS.entityOperation$RtmO)).equals("create")) {
        tgs.append("type ");
        tgs.append(name);
        tgs.append("CreatedEvent struct {");
        tgs.newLine();
        tgs.append(" ");
        tgs.append(name);
        tgs.append(" ");
        tgs.append(name);
        tgs.append(" `json:\"");
        tgs.append(nameLower);
        tgs.append("\"`");
        tgs.newLine();
        tgs.append(" Timestamp time.Time `json:\"timestamp\"`");
        tgs.newLine();
        tgs.append("}");
        tgs.newLine();
        tgs.newLine();
      }

      if (SEnumOperations.getMemberName0(SPropertyOperations.getEnum(op, PROPS.entityOperation$RtmO)).equals("update")) {
        tgs.append("type ");
        tgs.append(name);
        tgs.append("UpdatedEvent struct {");
        tgs.newLine();
        tgs.append(" ");
        tgs.append(name);
        tgs.append(" ");
        tgs.append(name);
        tgs.append(" `json:\"");
        tgs.append(nameLower);
        tgs.append("\"`");
        tgs.newLine();
        tgs.append(" Timestamp time.Time `json:\"timestamp\"`");
        tgs.newLine();
        tgs.append("}");
        tgs.newLine();
        tgs.newLine();
      }

      if (SEnumOperations.getMemberName0(SPropertyOperations.getEnum(op, PROPS.entityOperation$RtmO)).equals("delete")) {
        tgs.append("type ");
        tgs.append(name);
        tgs.append("DeletedEvent struct {");
        tgs.newLine();
        tgs.append(" ");
        tgs.append(name);
        tgs.append("ID string `json:\"");
        tgs.append(nameLower);
        tgs.append("_id\"`");
        tgs.newLine();
        tgs.append(" Timestamp time.Time `json:\"timestamp\"`");
        tgs.newLine();
        tgs.append("}");
        tgs.newLine();
        tgs.newLine();
      }

      if (SEnumOperations.getMemberName0(SPropertyOperations.getEnum(op, PROPS.entityOperation$RtmO)).equals("list")) {
        tgs.append("type ");
        tgs.append(name);
        tgs.append("ListRequest struct {");
        tgs.newLine();
        tgs.append(" Limit     int       `json:\"limit\"`");
        tgs.newLine();
        tgs.append(" Offset    int       `json:\"offset\"`");
        tgs.newLine();
        tgs.append(" Timestamp time.Time `json:\"timestamp\"`");
        tgs.newLine();
        tgs.append("}");
        tgs.newLine();
        tgs.newLine();
      }

      if (SEnumOperations.getMemberName0(SPropertyOperations.getEnum(op, PROPS.entityOperation$RtmO)).equals("get")) {
        tgs.append("type ");
        tgs.append(name);
        tgs.append("GetRequest struct {");
        tgs.newLine();
        tgs.append(" ");
        tgs.append(name);
        tgs.append("ID string `json:\"");
        tgs.append(nameLower);
        tgs.append("_id\"`");
        tgs.newLine();
        tgs.append(" Timestamp time.Time `json:\"timestamp\"`");
        tgs.newLine();
        tgs.append("}");
        tgs.newLine();
        tgs.newLine();
      }

    }

    tgs.append("type ");
    tgs.append(name);
    tgs.append("Handler struct {");
    tgs.newLine();
    tgs.append(" publisher     *events.Publisher");
    tgs.newLine();
    tgs.append(" subjectPrefix string");
    tgs.newLine();
    tgs.append("}");
    tgs.newLine();
    tgs.newLine();
    tgs.append("func New");
    tgs.append(name);
    tgs.append("Handler(pub *events.Publisher, subjectPrefix string) *");
    tgs.append(name);
    tgs.append("Handler {");
    tgs.newLine();
    tgs.append(" return &");
    tgs.append(name);
    tgs.append("Handler{");
    tgs.newLine();
    tgs.append("  publisher:     pub,");
    tgs.newLine();
    tgs.append("  subjectPrefix: subjectPrefix,");
    tgs.newLine();
    tgs.append(" }");
    tgs.newLine();
    tgs.append("}");
    tgs.newLine();
    tgs.newLine();

    for (SNode op : ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.operations$RrWf))) {
      String opName = EntityOperationHolder__BehaviorDescriptor.capitalize_id6DJmAW$mchD.invoke(op);
      String opKind = SEnumOperations.getMemberName0(SPropertyOperations.getEnum(op, PROPS.entityOperation$RtmO));

      tgs.append("func (s *");
      tgs.append(name);
      tgs.append("Handler) Handle");
      tgs.append(opName);
      tgs.append("(req core.Request) {");
      tgs.newLine();
      tgs.append(" ctx := req.Context()");
      tgs.newLine();
      tgs.append(" ctx, span := tracer.StartConsumer(ctx, \"");
      tgs.append(name);
      tgs.append(".Handle");
      tgs.append(opName);
      tgs.append("\")");
      tgs.newLine();
      tgs.append(" defer span.End()");
      tgs.newLine();
      tgs.append(" ctx = core.InjectContext(ctx, req.Headers())");
      tgs.newLine();
      tgs.append("logger.Info(ctx, \"request received\", logger.String(\"handler\", \"");
      tgs.append(name);
      tgs.append(".");
      tgs.append(opName);
      tgs.append("\"), logger.Int(\"bytes\", len(req.Data())))\n");
      tgs.newLine();

      if (opKind.equals("create")) {
        tgs.append(" var event ");
        tgs.append(name);
        tgs.append("CreatedEvent");
        tgs.newLine();
      }

      if (opKind.equals("update")) {
        tgs.append(" var event ");
        tgs.append(name);
        tgs.append("UpdatedEvent");
        tgs.newLine();
      }

      if (opKind.equals("delete")) {
        tgs.append(" var event ");
        tgs.append(name);
        tgs.append("DeletedEvent");
        tgs.newLine();

      }
      if (opKind.equals("list")) {
        tgs.append(" var event ");
        tgs.append(name);
        tgs.append("ListRequest");
        tgs.newLine();
      }

      if (opKind.equals("get")) {
        tgs.append(" var event ");
        tgs.append(name);
        tgs.append("GetRequest");
        tgs.newLine();
      }

      tgs.append(" if err := json.Unmarshal(req.Data(), &event); err != nil {");
      tgs.newLine();
      tgs.append("  span.RecordError(err)");
      tgs.newLine();
      tgs.append("  _ = req.RespondError(\"400\", \"invalid JSON: \" + err.Error(), nil)");
      tgs.newLine();
      tgs.append("  return");
      tgs.newLine();
      tgs.append(" }");
      tgs.newLine();
      tgs.newLine();

      if (opKind.equals("create")) {
        int validX = 0;
        for (SNode field : ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.fields$Rrud))) {
          if (!((boolean) Field__BehaviorDescriptor.hasAnotation_id6DJmAW$hoUl.invoke(field, "primaryKey")) && !((boolean) Field__BehaviorDescriptor.hasAnotation_id6DJmAW$hoUl.invoke(field, "auto")) && !((boolean) Field__BehaviorDescriptor.hasAnotation_id6DJmAW$hoUl.invoke(field, "hidden")) && !((boolean) Field__BehaviorDescriptor.hasAnotation_id6DJmAW$hoUl.invoke(field, "nullable"))) {
            if (validX == 0) {
              tgs.append(" if event.");
              tgs.append(name);
              tgs.append(".");
              tgs.append(Field__BehaviorDescriptor.capitalize_id5Lqw_By60m2.invoke(field));
              tgs.append(" == \"\"");
            }
            if (validX > 0) {
              tgs.append(" || event.");
              tgs.append(name);
              tgs.append(".");
              tgs.append(Field__BehaviorDescriptor.capitalize_id5Lqw_By60m2.invoke(field));
              tgs.append(" == \"\"");
            }
            validX = validX + 1;
          }
        }
        tgs.append(" {");
        tgs.newLine();
        tgs.append("  err := fmt.Errorf(\"invalid ");
        tgs.append(nameLower);
        tgs.append(" data: missing required fields\")");
        tgs.newLine();
        tgs.append("  span.RecordError(err)");
        tgs.newLine();
        tgs.append("  _ = req.RespondError(\"400\", err.Error(), nil)");
        tgs.newLine();
        tgs.append("  return");
        tgs.newLine();
        tgs.append(" }");
        tgs.newLine();

      }

      if (opKind.equals("update")) {
        tgs.append(" if event.");
        tgs.append(name);
        tgs.append(".");
        tgs.append(pkField);
        tgs.append(" == \"\" {");
        tgs.newLine();
        tgs.append("  err := fmt.Errorf(\"invalid ");
        tgs.append(nameLower);
        tgs.append(" data: missing ID\")");
        tgs.newLine();
        tgs.append("  span.RecordError(err)");
        tgs.newLine();
        tgs.append("  _ = req.RespondError(\"400\", err.Error(), nil)");
        tgs.newLine();
        tgs.append("  return");
        tgs.newLine();
        tgs.append(" }");
        tgs.newLine();
      }
      if (opKind.equals("delete")) {
        tgs.append(" if event.");
        tgs.append(name);
        tgs.append("ID == \"\" {");
        tgs.newLine();
        tgs.append("  err := fmt.Errorf(\"invalid request: missing ");
        tgs.append(nameLower);
        tgs.append(" ID\")");
        tgs.newLine();
        tgs.append("  span.RecordError(err)");
        tgs.newLine();
        tgs.append("  _ = req.RespondError(\"400\", err.Error(), nil)");
        tgs.newLine();
        tgs.append("  return");
        tgs.newLine();
        tgs.append(" }");
        tgs.newLine();
      }


      if (opKind.equals("get")) {
        tgs.append(" if event.");
        tgs.append(name);
        tgs.append("ID == \"\" {");
        tgs.newLine();
        tgs.append("  err := fmt.Errorf(\"invalid request: missing ");
        tgs.append(nameLower);
        tgs.append(" ID\")");
        tgs.newLine();
        tgs.append("  span.RecordError(err)");
        tgs.newLine();
        tgs.append("  _ = req.RespondError(\"400\", err.Error(), nil)");
        tgs.newLine();
        tgs.append("  return");
        tgs.newLine();
        tgs.append(" }");
        tgs.newLine();
      }


      if (opKind.equals("list")) {
        tgs.append(" if event.Limit < 0 || event.Offset < 0 {");
        tgs.newLine();
        tgs.append("  err := fmt.Errorf(\"invalid pagination parameters\")");
        tgs.newLine();
        tgs.append("  span.RecordError(err)");
        tgs.newLine();
        tgs.append("  _ = req.RespondError(\"400\", err.Error(), nil)");
        tgs.newLine();
        tgs.append("  return");
        tgs.newLine();
        tgs.append(" }");
        tgs.newLine();
      }

      tgs.newLine();
      tgs.append(" span.SetAttributes(");
      tgs.newLine();
      if (opKind.equals("create")) {
        tgs.append("  tracer.StringAttr(\"");
        tgs.append(nameLower);
        tgs.append(".id\", event.");
        tgs.append(name);
        tgs.append(".");
        tgs.append(pkField);
        tgs.append("),");
        tgs.newLine();
      }

      if (opKind.equals("update")) {
        tgs.append("  tracer.StringAttr(\"");
        tgs.append(nameLower);
        tgs.append(".id\", event.");
        tgs.append(name);
        tgs.append(".");
        tgs.append(pkField);
        tgs.append("),");
        tgs.newLine();
      }

      if (opKind.equals("delete")) {
        tgs.append("  tracer.StringAttr(\"");
        tgs.append(nameLower);
        tgs.append(".id\", event.");
        tgs.append(name);
        tgs.append("ID),");
        tgs.newLine();
      }

      if (opKind.equals("get")) {
        tgs.append("  tracer.StringAttr(\"");
        tgs.append(nameLower);
        tgs.append(".id\", event.");
        tgs.append(name);
        tgs.append("ID),");
        tgs.newLine();
      }

      tgs.append("  tracer.StringAttr(\"tenant.id\", req.Header(core.HeaderTenantID)),");
      tgs.newLine();
      tgs.append(" )");
      tgs.newLine();
      tgs.newLine();


      // this
      for (SNode prehook : ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.preHooksNamed$xIX))) {
        String prehookOpName = SEnumOperations.getMemberName0(SPropertyOperations.getEnum(prehook, PROPS.entityOperation$RtmO));
        if (prehookOpName.equals(opKind)) {
          for (SNode hook : Sequence.fromIterable(HookTypeHooksHolder__BehaviorDescriptor.getHooksSorted_id2H11bzboFUZ.invoke(prehook))) {
            String hName = Hook__BehaviorDescriptor.capitalize_id2H11bzbgoT7.invoke(hook);
            if (SPropertyOperations.getBoolean(hook, PROPS.isAsync$Nysa)) {
              tgs.append(" logger.Debug(ctx, \"hook dispatched\", logger.String(\"hook\", \"pre");
              tgs.append(opName);
              tgs.append(hName);
              tgs.append("\"), logger.String(\"phase\", \"pre\"),\n  logger.String(\"mode\", \"async\"))");
              tgs.newLine();
              tgs.append("_ = workerpool.AsyncWithCtx(ctx, func(c context.Context) {");
              tgs.newLine();
              tgs.append("   s.pre");
              tgs.append(opName);
              tgs.append(hName);
              tgs.append("(c, span, &event)");
              tgs.newLine();
              tgs.append(" })");
              tgs.newLine();
              tgs.newLine();
            } else {
              tgs.append(" logger.Debug(ctx, \"hook executing\", logger.String(\"hook\", \"pre");
              tgs.append(opName);
              tgs.append(hName);
              tgs.append("\"), logger.String(\"phase\", \"pre\"),\n  logger.String(\"mode\", \"sync\"))");
              tgs.newLine();
              tgs.append(" if err := s.pre");
              tgs.append(opName);
              tgs.append(hName);
              tgs.append("(ctx, span, &event); err != nil {");
              tgs.newLine();
              tgs.append("  logger.Error(ctx, \"hook failed\", logger.String(\"hook\", \"pre");
              tgs.append(opName);
              tgs.append(hName);
              tgs.append("\"), logger.Err(err))");
              tgs.newLine();
              tgs.append("  span.RecordError(err)");
              tgs.newLine();
              tgs.append("  _ = req.RespondError(\"400\", \"pre-hook: \" + err.Error(), nil)");
              tgs.newLine();
              tgs.append("  return");
              tgs.newLine();
              tgs.append(" }");
              tgs.newLine();
              tgs.newLine();
            }
          }
        }
      }

      tgs.append(" dalSubject := s.subjectPrefix + \".");
      tgs.append(nameLower);
      tgs.append(".db.");
      tgs.append(opKind);
      tgs.append("\"");
      tgs.newLine();
      tgs.append(" outMsg := &nats.Msg{Data: req.Data()}");
      tgs.newLine();
      tgs.append(" outMsg.Header = core.ExtractHeaders(ctx, nil)");
      tgs.newLine();
      tgs.append(" outMsg.Header.Set(\"X-Business-Validated\", \"true\")");
      tgs.newLine();
      tgs.newLine();
      tgs.append(" dalCtx, dalCancel := context.WithTimeout(ctx, 10*time.Second)");
      tgs.newLine();
      tgs.append(" defer dalCancel()");
      tgs.newLine();
      tgs.newLine();
      tgs.append(" reply, err := s.publisher.Request(dalCtx, dalSubject, outMsg)");
      tgs.newLine();
      tgs.append(" if err != nil {");
      tgs.newLine();
      tgs.append("  span.RecordError(err)");
      tgs.newLine();
      tgs.append("  _ = req.RespondError(\"500\", \"DAL request error: \" + err.Error(), nil)");
      tgs.newLine();
      tgs.append("  return");
      tgs.newLine();
      tgs.append(" }");
      tgs.newLine();
      tgs.newLine();
      tgs.append("logger.Info(ctx, \"DAL reply received\", logger.String(\"handler\", \"");
      tgs.append(name);
      tgs.append(".");
      tgs.append(opKind);
      tgs.append("\"), logger.Int(\"bytes\", len(reply.Data)))");
      tgs.newLine();

      boolean hasPostHook = false;
      for (SNode posthook : ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.postHooksNamed$xXY))) {
        if (SEnumOperations.getMemberName0(SPropertyOperations.getEnum(posthook, PROPS.entityOperation$RtmO)).equals(opKind)) {
          hasPostHook = true;
          break;
        }
      }
      if (hasPostHook) {
        tgs.append(" responseData := reply.Data");
        tgs.newLine();
        for (SNode postHookHolder : ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.postHooksNamed$xXY))) {
          if (SEnumOperations.getMemberName0(SPropertyOperations.getEnum(postHookHolder, PROPS.entityOperation$RtmO)).equals(opKind)) {
            for (SNode h : ListSequence.fromList(SLinkOperations.getChildren(postHookHolder, LINKS.Hooks$E6NN))) {
              if (SPropertyOperations.getBoolean(h, PROPS.isAsync$Nysa)) {
                tgs.append(" logger.Debug(ctx, \"hook dispatched\", logger.String(\"hook\", \"post");
                tgs.append(opName);
                tgs.append(Hook__BehaviorDescriptor.capitalize_id2H11bzbgoT7.invoke(h));
                tgs.append("\"), logger.String(\"phase\", \"post\"),\n  logger.String(\"mode\", \"async\"))");
                tgs.newLine();
                tgs.append(" _ = workerpool.AsyncWithCtx(ctx, func(c context.Context) {");
                tgs.newLine();
                tgs.append("  s.post");
                tgs.append(opName);
                tgs.append(Hook__BehaviorDescriptor.capitalize_id2H11bzbgoT7.invoke(h));
                tgs.append("(c, span, &event, responseData)");
                tgs.newLine();
                tgs.append(" })");
                tgs.newLine();
                tgs.newLine();
              } else {

                tgs.append(" logger.Debug(ctx, \"hook executing\", logger.String(\"hook\", \"post");
                tgs.append(opName);
                tgs.append(Hook__BehaviorDescriptor.capitalize_id2H11bzbgoT7.invoke(h));
                tgs.append("\"), logger.String(\"phase\", \"post\"),\n  logger.String(\"mode\", \"sync\"))");
                tgs.newLine();
                tgs.append(" responseData = s.post");
                tgs.append(opName);
                tgs.append(Hook__BehaviorDescriptor.capitalize_id2H11bzbgoT7.invoke(h));
                tgs.append("(ctx, span, &event, responseData)");
                tgs.newLine();
              }
            }
          }
        }
        tgs.append(" _ = req.Respond(responseData)");
        tgs.newLine();
      } else {
        tgs.append(" _ = req.Respond(reply.Data)");
        tgs.newLine();
      }
      tgs.append("}");
      tgs.newLine();
      tgs.newLine();

    }

    tgs.append("// #HOOKS_START");
    tgs.newLine();
    for (SNode prehooksHolder : ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.preHooksNamed$xIX))) {
      String opKind = SEnumOperations.getMemberName0(SPropertyOperations.getEnum(prehooksHolder, PROPS.entityOperation$RtmO));
      String opName = EntityOperationHolder__BehaviorDescriptor.capitalize_id6DJmAW$mchD.invoke(prehooksHolder);

      // determine event type
      String eventType = "";
      if (opKind.equals("create")) {
        eventType = name + "CreatedEvent";
      }
      if (opKind.equals("update")) {
        eventType = name + "UpdatedEvent";
      }
      if (opKind.equals("delete")) {
        eventType = name + "DeletedEvent";
      }
      if (opKind.equals("get")) {
        eventType = name + "GetRequest";
      }
      if (opKind.equals("list")) {
        eventType = name + "ListRequest";
      }

      for (SNode hook : ListSequence.fromList(SLinkOperations.getChildren(prehooksHolder, LINKS.Hooks$E6NN))) {
        String hname = Hook__BehaviorDescriptor.capitalize_id2H11bzbgoT7.invoke(hook);

        if (SPropertyOperations.getBoolean(hook, PROPS.isAsync$Nysa)) {
          tgs.append("func (s *");
          tgs.append(name);
          tgs.append("Handler) pre");
          tgs.append(opName);
          tgs.append(hname);
          tgs.append("(ctx context.Context, span tracer.Span, event *");
          tgs.append(eventType);
          tgs.append(") {");
          tgs.newLine();
          tgs.append("ctx, hookSpan := tracer.Start(ctx, \"hook.pre.");
          tgs.append(name);
          tgs.append(".");
          tgs.append(opKind);
          tgs.append(".");
          tgs.append(hname);
          tgs.append("\")");
          tgs.newLine();
          tgs.append("defer hookSpan.End()");
          tgs.newLine();
          tgs.append("\t// TODO: implement");
          tgs.newLine();
          tgs.append("hookSpan.SetOK()");
          tgs.newLine();
          tgs.append("}");
          tgs.newLine();
          tgs.newLine();
        } else {
          tgs.append("func (s *");
          tgs.append(name);
          tgs.append("Handler) pre");
          tgs.append(opName);
          tgs.append(hname);
          tgs.append("(ctx context.Context, span tracer.Span, event *");
          tgs.append(eventType);
          tgs.append(") error {");
          tgs.newLine();
          tgs.append("ctx, hookSpan := tracer.Start(ctx, \"hook.pre.");
          tgs.append(name);
          tgs.append(".");
          tgs.append(opKind);
          tgs.append(".");
          tgs.append(hname);
          tgs.append("\")");
          tgs.newLine();
          tgs.append("defer hookSpan.End()");
          tgs.newLine();
          tgs.append("\t// TODO: implement");
          tgs.newLine();
          tgs.append("hookSpan.SetOK()");
          tgs.newLine();
          tgs.append("   return nil");
          tgs.newLine();
          tgs.append("}");
          tgs.newLine();
          tgs.newLine();
        }
      }

    }
    for (SNode posthooksHolder : ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.postHooksNamed$xXY))) {
      String opKind = SEnumOperations.getMemberName0(SPropertyOperations.getEnum(posthooksHolder, PROPS.entityOperation$RtmO));
      String opName = EntityOperationHolder__BehaviorDescriptor.capitalize_id6DJmAW$mchD.invoke(posthooksHolder);

      // determine event type
      String eventType = "";
      if (opKind.equals("create")) {
        eventType = name + "CreatedEvent";
      }
      if (opKind.equals("update")) {
        eventType = name + "UpdatedEvent";
      }
      if (opKind.equals("delete")) {
        eventType = name + "DeletedEvent";
      }
      if (opKind.equals("get")) {
        eventType = name + "GetRequest";
      }
      if (opKind.equals("list")) {
        eventType = name + "ListRequest";
      }

      for (SNode hook : ListSequence.fromList(SLinkOperations.getChildren(posthooksHolder, LINKS.Hooks$E6NN))) {
        String hname = Hook__BehaviorDescriptor.capitalize_id2H11bzbgoT7.invoke(hook);
        if (SPropertyOperations.getBoolean(hook, PROPS.isAsync$Nysa)) {
          tgs.append("func (s *");
          tgs.append(name);
          tgs.append("Handler) post");
          tgs.append(opName);
          tgs.append(hname);
          tgs.append("(ctx context.Context, span tracer.Span, event *");
          tgs.append(eventType);
          tgs.append(", data []byte) {");
          tgs.newLine();
          tgs.append("ctx, hookSpan := tracer.Start(ctx, \"hook.post.");
          tgs.append(name);
          tgs.append(".");
          tgs.append(opKind);
          tgs.append(".");
          tgs.append(hname);
          tgs.append("\")");
          tgs.newLine();
          tgs.append("defer hookSpan.End()");
          tgs.newLine();
          tgs.append("\t// TODO: implement");
          tgs.newLine();
          tgs.append("hookSpan.SetOK()");
          tgs.newLine();

          tgs.append("}");
          tgs.newLine();
          tgs.newLine();
        } else {
          tgs.append("func (s *");
          tgs.append(name);
          tgs.append("Handler) post");
          tgs.append(opName);
          tgs.append(hname);
          tgs.append("(ctx context.Context, span tracer.Span, event *");
          tgs.append(eventType);
          tgs.append(", data []byte) []byte {");
          tgs.newLine();
          tgs.append("ctx, hookSpan := tracer.Start(ctx, \"hook.post.");
          tgs.append(name);
          tgs.append(".");
          tgs.append(opKind);
          tgs.append(".");
          tgs.append(hname);
          tgs.append("\")");
          tgs.newLine();
          tgs.append("defer hookSpan.End()");
          tgs.newLine();
          tgs.append("\t// TODO: implement");
          tgs.newLine();
          tgs.append("hookSpan.SetOK()");
          tgs.newLine();

          tgs.append("   return data");
          tgs.newLine();
          tgs.append("}");
          tgs.newLine();
          tgs.newLine();
        }
      }

    }

    tgs.append("// #HOOKS_END");
    tgs.newLine();

    ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.relations$Mn4T)).visitAll((it) -> {
      tgs.appendNode(it);
      tgs.newLine();
    });
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
    /*package*/ static final SProperty entityOperation$RtmO = MetaAdapterFactory.getProperty(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac89L, 0x6a6f5a6f2407ac8bL, "entityOperation");
    /*package*/ static final SProperty isAsync$Nysa = MetaAdapterFactory.getProperty(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x2b4104b8cb107debL, 0x2b4104b8cb8c2ff7L, "isAsync");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink fields$Rrud = MetaAdapterFactory.getContainmentLink(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac7eL, 0x6a6f5a6f2407ac84L, "fields");
    /*package*/ static final SContainmentLink operations$RrWf = MetaAdapterFactory.getContainmentLink(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac7eL, 0x6a6f5a6f2407ac86L, "operations");
    /*package*/ static final SContainmentLink preHooksNamed$xIX = MetaAdapterFactory.getContainmentLink(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac7eL, 0x2b4104b8cb107decL, "preHooksNamed");
    /*package*/ static final SContainmentLink postHooksNamed$xXY = MetaAdapterFactory.getContainmentLink(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac7eL, 0x2b4104b8cb107dedL, "postHooksNamed");
    /*package*/ static final SContainmentLink Hooks$E6NN = MetaAdapterFactory.getContainmentLink(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x2b4104b8cb107de9L, 0x2b4104b8cb107deaL, "Hooks");
    /*package*/ static final SContainmentLink relations$Mn4T = MetaAdapterFactory.getContainmentLink(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac7eL, 0x210dfbd5ddf5be7aL, "relations");
  }
}
