package UserManagement.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SEnumOperations;
import UserManagement.behavior.RelationOperationHolder__BehaviorDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class Relation_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    // new

    String fromName = SPropertyOperations.getString(SNodeOperations.getNodeAncestor(ctx.getPrimaryInput(), CONCEPTS.Entity$iI, false, false), PROPS.name$MnvL);
    String toName = SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.to$R_jq), PROPS.name$MnvL);
    String fromNameLow = fromName.toLowerCase();
    String tonameLow = toName.toLowerCase();

    tgs.newLine();

    for (SNode op : ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.operations$REVM))) {
      String opKind = SEnumOperations.getMemberName0(SPropertyOperations.getEnum(op, PROPS.relationOperation$RG8k));

      if (opKind.equals("assign")) {
        tgs.append("type ");
        tgs.append(fromName);
        tgs.append(toName);
        tgs.append("AssignedEvent struct {");
        tgs.newLine();
        tgs.append(" ");
        tgs.append(fromName);
        tgs.append("ID string `json:\"");
        tgs.append(fromNameLow);
        tgs.append("_id\"`");
        tgs.newLine();
        tgs.append(" ");
        tgs.append(toName);
        tgs.append("ID string `json:\"");
        tgs.append(tonameLow);
        tgs.append("_id\"`");
        tgs.newLine();
        tgs.append(" Timestamp time.Time `json:\"timestamp\"`");
        tgs.newLine();
        tgs.append("}");
        tgs.newLine();
        tgs.newLine();
      }

      if (opKind.equals("remove")) {
        tgs.append("type ");
        tgs.append(fromName);
        tgs.append(toName);
        tgs.append("RemovedEvent struct {");
        tgs.newLine();
        tgs.append(" ");
        tgs.append(fromName);
        tgs.append("ID string `json:\"");
        tgs.append(fromNameLow);
        tgs.append("_id\"`");
        tgs.newLine();
        tgs.append(" ");
        tgs.append(toName);
        tgs.append("ID string `json:\"");
        tgs.append(tonameLow);
        tgs.append("_id\"`");
        tgs.newLine();
        tgs.append(" Timestamp time.Time `json:\"timestamp\"`");
        tgs.newLine();
        tgs.append("}");
        tgs.newLine();
        tgs.newLine();
      }

      if (opKind.equals("list")) {
        tgs.append("type ");
        tgs.append(fromName);
        tgs.append(toName);
        tgs.append("ListRequest struct {");
        tgs.newLine();
        tgs.append(" ");
        tgs.append(fromName);
        tgs.append("ID string `json:\"");
        tgs.append(fromNameLow);
        tgs.append("_id\"`");
        tgs.newLine();
        tgs.append(" Limit     int       `json:\"limit\"`");
        tgs.newLine();
        tgs.append(" Offset    int       `json:\"offset\"`");
        tgs.newLine();
        tgs.append(" Timestamp time.Time `json:\"timestamp\"`");
        tgs.newLine();
        tgs.append("}");
        tgs.newLine();
        tgs.newLine();
      }

    }

    tgs.append("type ");
    tgs.append(fromName);
    tgs.append(toName);
    tgs.append("Handler struct {");
    tgs.newLine();
    tgs.append(" publisher     *events.Publisher");
    tgs.newLine();
    tgs.append(" subjectPrefix string");
    tgs.newLine();
    tgs.append("}");
    tgs.newLine();
    tgs.newLine();
    tgs.append("func New");
    tgs.append(fromName);
    tgs.append(toName);
    tgs.append("Handler(pub *events.Publisher, subjectPrefix string) *");
    tgs.append(fromName);
    tgs.append(toName);
    tgs.append("Handler {");
    tgs.newLine();
    tgs.append(" return &");
    tgs.append(fromName);
    tgs.append(toName);
    tgs.append("Handler{");
    tgs.newLine();
    tgs.append("  publisher:     pub,");
    tgs.newLine();
    tgs.append("  subjectPrefix: subjectPrefix,");
    tgs.newLine();
    tgs.append(" }");
    tgs.newLine();
    tgs.append("}");
    tgs.newLine();
    tgs.newLine();


    for (SNode op : ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.operations$REVM))) {
      String opKind = SEnumOperations.getMemberName0(SPropertyOperations.getEnum(op, PROPS.relationOperation$RG8k));
      String opName = RelationOperationHolder__BehaviorDescriptor.capitalize_id6LRrEr56jrv.invoke(op);

      tgs.append("func (s *");
      tgs.append(fromName);
      tgs.append(toName);
      tgs.append("Handler) Handle");
      tgs.append(opName);
      tgs.append("(req core.Request) {");
      tgs.newLine();
      tgs.append(" ctx := req.Context()");
      tgs.newLine();
      tgs.append(" ctx, span := tracer.StartConsumer(ctx, \"");
      tgs.append(fromName);
      tgs.append(toName);
      tgs.append(".Handle");
      tgs.append(opName);
      tgs.append("\")");
      tgs.newLine();
      tgs.append(" defer span.End()");
      tgs.newLine();
      tgs.append("logger.Info(ctx, \"request received\", logger.String(\"handler\", \"");
      tgs.append(fromName);
      tgs.append(toName);
      tgs.append(".");
      tgs.append(opName);
      tgs.append("\"), logger.Int(\"bytes\", len(req.Data())))\n");
      tgs.append(" ctx = core.InjectContext(ctx, req.Headers())");
      tgs.newLine();
      tgs.newLine();

      if (opKind.equals("assign")) {
        tgs.append(" var event ");
        tgs.append(fromName);
        tgs.append(toName);
        tgs.append("AssignedEvent");
        tgs.newLine();
      }

      if (opKind.equals("remove")) {
        tgs.append(" var event ");
        tgs.append(fromName);
        tgs.append(toName);
        tgs.append("RemovedEvent");
        tgs.newLine();
      }

      if (opKind.equals("list")) {
        tgs.append(" var event ");
        tgs.append(fromName);
        tgs.append(toName);
        tgs.append("ListRequest");
        tgs.newLine();
      }

      tgs.append(" if err := json.Unmarshal(req.Data(), &event); err != nil {");
      tgs.newLine();
      tgs.append("  span.RecordError(err)");
      tgs.newLine();
      tgs.append("  _ = req.RespondError(\"400\", \"invalid JSON: \" + err.Error(), nil)");
      tgs.newLine();
      tgs.append("  return");
      tgs.newLine();
      tgs.append(" }");
      tgs.newLine();
      tgs.newLine();

      if (opKind.equals("assign") || opKind.equals("remove")) {
        tgs.append(" if event.");
        tgs.append(fromName);
        tgs.append("ID == \"\" || event.");
        tgs.append(toName);
        tgs.append("ID == \"\" {");
        tgs.newLine();
        tgs.append("  err := fmt.Errorf(\"invalid data: missing ");
        tgs.append(fromNameLow);
        tgs.append(" or ");
        tgs.append(tonameLow);
        tgs.append(" ID\")");
        tgs.newLine();
        tgs.append("  span.RecordError(err)");
        tgs.newLine();
        tgs.append("  _ = req.RespondError(\"400\", err.Error(), nil)");
        tgs.newLine();
        tgs.append("  return");
        tgs.newLine();
        tgs.append(" }");
        tgs.newLine();
      }

      if (opKind.equals("list")) {
        tgs.append(" if event.");
        tgs.append(fromName);
        tgs.append("ID == \"\" {");
        tgs.newLine();
        tgs.append("  err := fmt.Errorf(\"invalid request: missing ");
        tgs.append(fromNameLow);
        tgs.append(" ID\")");
        tgs.newLine();
        tgs.append("  span.RecordError(err)");
        tgs.newLine();
        tgs.append("  _ = req.RespondError(\"400\", err.Error(), nil)");
        tgs.newLine();
        tgs.append("  return");
        tgs.newLine();
        tgs.append(" }");
        tgs.newLine();
      }

      tgs.newLine();
      tgs.append(" span.SetAttributes(");
      tgs.newLine();

      if (opKind.equals("assign") || opKind.equals("remove")) {
        tgs.append("  tracer.StringAttr(\"");
        tgs.append(fromNameLow);
        tgs.append(".id\", event.");
        tgs.append(fromName);
        tgs.append("ID),");
        tgs.newLine();
        tgs.append("  tracer.StringAttr(\"");
        tgs.append(tonameLow);
        tgs.append(".id\", event.");
        tgs.append(toName);
        tgs.append("ID),");
        tgs.newLine();
      }
      if (opKind.equals("list")) {
        tgs.append("  tracer.StringAttr(\"");
        tgs.append(fromNameLow);
        tgs.append(".id\", event.");
        tgs.append(fromName);
        tgs.append("ID),");
        tgs.newLine();
      }


      tgs.append("  tracer.StringAttr(\"tenant.id\", req.Header(core.HeaderTenantID)),");
      tgs.newLine();
      tgs.append(" )");
      tgs.newLine();
      tgs.newLine();

      tgs.append(" if err := s.pre");
      tgs.append(opName);
      tgs.append("Hook(ctx, span, &event); err != nil {");
      tgs.newLine();
      tgs.append("  span.RecordError(err)");
      tgs.newLine();
      tgs.append("  _ = req.RespondError(\"400\", \"pre-hook: \" + err.Error(), nil)");
      tgs.newLine();
      tgs.append("  return");
      tgs.newLine();
      tgs.append(" }");
      tgs.newLine();
      tgs.newLine();

      tgs.append(" dalSubject := s.subjectPrefix + \".");
      tgs.append(fromNameLow);
      tgs.append(".");
      tgs.append(tonameLow);
      tgs.append(".db.");
      tgs.append(opKind);
      tgs.append("\"");
      tgs.newLine();
      tgs.append(" outMsg := &nats.Msg{Data: req.Data()}");
      tgs.newLine();
      tgs.append(" outMsg.Header = core.ExtractHeaders(ctx, nil)");
      tgs.newLine();
      tgs.append(" outMsg.Header.Set(\"X-Business-Validated\", \"true\")");
      tgs.newLine();
      tgs.newLine();
      tgs.append(" dalCtx, dalCancel := context.WithTimeout(ctx, 10*time.Second)");
      tgs.newLine();
      tgs.append(" defer dalCancel()");
      tgs.newLine();
      tgs.newLine();
      tgs.append(" reply, err := s.publisher.Request(dalCtx, dalSubject, outMsg)");
      tgs.newLine();
      tgs.append(" if err != nil {");
      tgs.newLine();
      tgs.append("  span.RecordError(err)");
      tgs.newLine();
      tgs.append("  _ = req.RespondError(\"500\", \"DAL request error: \" + err.Error(), nil)");
      tgs.newLine();
      tgs.append("  return");
      tgs.newLine();
      tgs.append(" }");
      tgs.newLine();
      tgs.newLine();
      tgs.append(" logger.Info(ctx, \"DAL reply received\", logger.String(\"handler\", \"");
      tgs.append(fromName);
      tgs.append(toName);
      tgs.append(".");
      tgs.append(opKind);
      tgs.append("\"), logger.Int(\"bytes\", len(reply.Data)))\n");
      tgs.newLine();

      tgs.append(" responseData := s.post");
      tgs.append(opName);
      tgs.append("Hook(ctx, span, &event, reply.Data)");
      tgs.newLine();
      tgs.append(" _ = req.Respond(responseData)");
      tgs.newLine();
      tgs.append("}");
      tgs.newLine();
      tgs.newLine();

    }

    tgs.append("// #HOOKS_START");
    tgs.newLine();


    for (SNode op : ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.operations$REVM))) {
      String opKind = SEnumOperations.getMemberName0(SPropertyOperations.getEnum(op, PROPS.relationOperation$RG8k));
      String hookName = RelationOperationHolder__BehaviorDescriptor.capitalize_id6LRrEr56jrv.invoke(op);

      if (opKind.equals("assign")) {
        tgs.append("func (s *");
        tgs.append(fromName);
        tgs.append(toName);
        tgs.append("Handler) pre");
        tgs.append(hookName);
        tgs.append("Hook(ctx context.Context, span tracer.Span, event *");
        tgs.append(fromName);
        tgs.append(toName);
        tgs.append("AssignedEvent) error {");
        tgs.newLine();
        tgs.append(" return nil");
        tgs.newLine();
        tgs.append("}");
        tgs.newLine();
        tgs.newLine();
        tgs.append("func (s *");
        tgs.append(fromName);
        tgs.append(toName);
        tgs.append("Handler) post");
        tgs.append(hookName);
        tgs.append("Hook(ctx context.Context, span tracer.Span, event *");
        tgs.append(fromName);
        tgs.append(toName);
        tgs.append("AssignedEvent, data []byte) []byte {");
        tgs.newLine();
        tgs.append(" return data");
        tgs.newLine();
        tgs.append("}");
        tgs.newLine();
        tgs.newLine();
      }

      if (opKind.equals("remove")) {
        tgs.append("func (s *");
        tgs.append(fromName);
        tgs.append(toName);
        tgs.append("Handler) pre");
        tgs.append(hookName);
        tgs.append("Hook(ctx context.Context, span tracer.Span, event *");
        tgs.append(fromName);
        tgs.append(toName);
        tgs.append("RemovedEvent) error {");
        tgs.newLine();
        tgs.append(" return nil");
        tgs.newLine();
        tgs.append("}");
        tgs.newLine();
        tgs.newLine();
        tgs.append("func (s *");
        tgs.append(fromName);
        tgs.append(toName);
        tgs.append("Handler) post");
        tgs.append(hookName);
        tgs.append("Hook(ctx context.Context, span tracer.Span, event *");
        tgs.append(fromName);
        tgs.append(toName);
        tgs.append("RemovedEvent, data []byte) []byte {");
        tgs.newLine();
        tgs.append(" return data");
        tgs.newLine();
        tgs.append("}");
        tgs.newLine();
        tgs.newLine();
      }

      if (opKind.equals("list")) {
        tgs.append("func (s *");
        tgs.append(fromName);
        tgs.append(toName);
        tgs.append("Handler) pre");
        tgs.append(hookName);
        tgs.append("Hook(ctx context.Context, span tracer.Span, event *");
        tgs.append(fromName);
        tgs.append(toName);
        tgs.append("ListRequest) error {");
        tgs.newLine();
        tgs.append(" return nil");
        tgs.newLine();
        tgs.append("}");
        tgs.newLine();
        tgs.newLine();
        tgs.append("func (s *");
        tgs.append(fromName);
        tgs.append(toName);
        tgs.append("Handler) post");
        tgs.append(hookName);
        tgs.append("Hook(ctx context.Context, span tracer.Span, event *");
        tgs.append(fromName);
        tgs.append(toName);
        tgs.append("ListRequest, data []byte) []byte {");
        tgs.newLine();
        tgs.append(" return data");
        tgs.newLine();
        tgs.append("}");
        tgs.newLine();
        tgs.newLine();
      }

    }

    tgs.append("// #HOOKS_END");
    tgs.newLine();

  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Entity$iI = MetaAdapterFactory.getConcept(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac7eL, "UserManagement.structure.Entity");
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
    /*package*/ static final SProperty relationOperation$RG8k = MetaAdapterFactory.getProperty(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac9cL, 0x6a6f5a6f2407ac9eL, "relationOperation");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink to$R_jq = MetaAdapterFactory.getReferenceLink(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac8fL, 0x6a6f5a6f2407ac97L, "to");
    /*package*/ static final SContainmentLink operations$REVM = MetaAdapterFactory.getContainmentLink(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac8fL, 0x6a6f5a6f2407ac9aL, "operations");
  }
}
