package UserManagement.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import UserManagement.behavior.Entity__BehaviorDescriptor;
import UserManagement.behavior.Field__BehaviorDescriptor;
import UserManagement.behavior.Relation__BehaviorDescriptor;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class SqlSchem_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);

    tgs.append("-- Auto-generated SQL for ");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.name$MnvL));
    tgs.newLine();
    tgs.append("-- Schema: ");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.dbSchema$kn9b));
    tgs.newLine();
    tgs.newLine();
    tgs.append("CREATE SCHEMA IF NOT EXISTS ");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.dbSchema$kn9b));
    tgs.append(";");
    tgs.newLine();
    tgs.newLine();

    for (SNode e : ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.entityrefs$ko5f))) {
      tgs.append("-- Table: ");
      tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.dbSchema$kn9b));
      tgs.append(".");
      tgs.append(Entity__BehaviorDescriptor.tableName_id6DJmAW$e3L$.invoke(SLinkOperations.getTarget(e, LINKS.entity$k9hN)));
      tgs.newLine();
      tgs.append("CREATE TABLE IF NOT EXISTS ");
      tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.dbSchema$kn9b));
      tgs.append(".");
      tgs.append(Entity__BehaviorDescriptor.tableName_id6DJmAW$e3L$.invoke(SLinkOperations.getTarget(e, LINKS.entity$k9hN)));
      tgs.append(" (");
      tgs.newLine();
      int fieldInx = 0;
      for (SNode f : ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(e, LINKS.entity$k9hN), LINKS.fields$Rrud))) {
        if (fieldInx > 0) {
          tgs.append(",");
          tgs.newLine();
        }
        if ((boolean) Field__BehaviorDescriptor.hasAnotation_id6DJmAW$hoUl.invoke(f, "primaryKey")) {
          tgs.append(" ");
          tgs.append(Field__BehaviorDescriptor.dbName_id6DJmAW$7pGu.invoke(f));
          tgs.append(" ");
          tgs.append(Field__BehaviorDescriptor.sqlType_id6DJmAW$aWx9.invoke(f));
          tgs.append(" PRIMARY KEY DEFAULT gen_random_uuid()");
        }
        if (!((boolean) Field__BehaviorDescriptor.hasAnotation_id6DJmAW$hoUl.invoke(f, "primaryKey")) && !((boolean) Field__BehaviorDescriptor.hasAnotation_id6DJmAW$hoUl.invoke(f, "nullable")) && !((boolean) Field__BehaviorDescriptor.hasAnotation_id6DJmAW$hoUl.invoke(f, "auto")) && !((boolean) Field__BehaviorDescriptor.hasAnotation_id6DJmAW$hoUl.invoke(f, "unique"))) {
          tgs.append(" ");
          tgs.append(Field__BehaviorDescriptor.dbName_id6DJmAW$7pGu.invoke(f));
          tgs.append(" ");
          tgs.append(Field__BehaviorDescriptor.sqlType_id6DJmAW$aWx9.invoke(f));
          tgs.append(" NOT NULL");
        }
        if (!((boolean) Field__BehaviorDescriptor.hasAnotation_id6DJmAW$hoUl.invoke(f, "primaryKey")) && !((boolean) Field__BehaviorDescriptor.hasAnotation_id6DJmAW$hoUl.invoke(f, "nullable")) && !((boolean) Field__BehaviorDescriptor.hasAnotation_id6DJmAW$hoUl.invoke(f, "auto")) && ((boolean) Field__BehaviorDescriptor.hasAnotation_id6DJmAW$hoUl.invoke(f, "unique"))) {
          tgs.append(" ");
          tgs.append(Field__BehaviorDescriptor.dbName_id6DJmAW$7pGu.invoke(f));
          tgs.append(" ");
          tgs.append(Field__BehaviorDescriptor.sqlType_id6DJmAW$aWx9.invoke(f));
          tgs.append(" NOT NULL UNIQUE");
        }
        if (!((boolean) Field__BehaviorDescriptor.hasAnotation_id6DJmAW$hoUl.invoke(f, "primaryKey")) && ((boolean) Field__BehaviorDescriptor.hasAnotation_id6DJmAW$hoUl.invoke(f, "nullable"))) {
          tgs.append(" ");
          tgs.append(Field__BehaviorDescriptor.dbName_id6DJmAW$7pGu.invoke(f));
          tgs.append(" ");
          tgs.append(Field__BehaviorDescriptor.sqlType_id6DJmAW$aWx9.invoke(f));
        }
        if (!((boolean) Field__BehaviorDescriptor.hasAnotation_id6DJmAW$hoUl.invoke(f, "primaryKey")) && ((boolean) Field__BehaviorDescriptor.hasAnotation_id6DJmAW$hoUl.invoke(f, "auto"))) {
          tgs.append(" ");
          tgs.append(Field__BehaviorDescriptor.dbName_id6DJmAW$7pGu.invoke(f));
          tgs.append(" ");
          tgs.append(Field__BehaviorDescriptor.sqlType_id6DJmAW$aWx9.invoke(f));
          tgs.append(" NOT NULL DEFAULT NOW()");
        }
        fieldInx++;
      }
      tgs.newLine();
      tgs.append(");");
      tgs.newLine();
      tgs.newLine();

      for (SNode f : ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(e, LINKS.entity$k9hN), LINKS.fields$Rrud))) {
        if ((boolean) Field__BehaviorDescriptor.hasAnotation_id6DJmAW$hoUl.invoke(f, "indexed")) {
          tgs.append("CREATE INDEX IF NOT EXISTS idx_");
          tgs.append(Entity__BehaviorDescriptor.tableName_id6DJmAW$e3L$.invoke(SLinkOperations.getTarget(e, LINKS.entity$k9hN)));
          tgs.append("_");
          tgs.append(Field__BehaviorDescriptor.dbName_id6DJmAW$7pGu.invoke(f));
          tgs.append(" ON ");
          tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.dbSchema$kn9b));
          tgs.append(".");
          tgs.append(Entity__BehaviorDescriptor.tableName_id6DJmAW$e3L$.invoke(SLinkOperations.getTarget(e, LINKS.entity$k9hN)));
          tgs.append("(");
          tgs.append(Field__BehaviorDescriptor.dbName_id6DJmAW$7pGu.invoke(f));
          tgs.append(");");
          tgs.newLine();
        }
      }
      tgs.newLine();
    }

    for (SNode rref : ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.relations$kokg))) {
      SNode r = SLinkOperations.getTarget(rref, LINKS.relation$kafN);
      tgs.append("-- Junction table: ");
      tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.dbSchema$kn9b));
      tgs.append(".");
      tgs.append(Relation__BehaviorDescriptor.tableName_id6DJmAW$ebFg.invoke(r));
      tgs.newLine();
      tgs.append("CREATE TABLE IF NOT EXISTS ");
      tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.dbSchema$kn9b));
      tgs.append(".");
      tgs.append(Relation__BehaviorDescriptor.tableName_id6DJmAW$ebFg.invoke(r));
      tgs.append(" (");
      tgs.newLine();

      tgs.append(" ");
      tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(r, LINKS.from$R$Po), PROPS.name$MnvL).toLowerCase());
      tgs.append("_id UUID NOT NULL REFERENCES ");
      tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.dbSchema$kn9b));
      tgs.append(".");
      tgs.append(Entity__BehaviorDescriptor.tableName_id6DJmAW$e3L$.invoke(SLinkOperations.getTarget(r, LINKS.from$R$Po)));
      tgs.append("(id) ON DELETE CASCADE,");
      tgs.newLine();
      tgs.append(" ");
      tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(r, LINKS.to$R_jq), PROPS.name$MnvL).toLowerCase());
      tgs.append("_id UUID NOT NULL REFERENCES ");
      tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.dbSchema$kn9b));
      tgs.append(".");
      tgs.append(Entity__BehaviorDescriptor.tableName_id6DJmAW$e3L$.invoke(SLinkOperations.getTarget(r, LINKS.to$R_jq)));
      tgs.append("(id) ON DELETE CASCADE");
      for (SNode fex : ListSequence.fromList(SLinkOperations.getChildren(r, LINKS.extraFields$RLJf))) {
        tgs.append(",");
        tgs.newLine();
        if ((boolean) Field__BehaviorDescriptor.hasAnotation_id6DJmAW$hoUl.invoke(fex, "auto")) {
          tgs.append(" ");
          tgs.append(Field__BehaviorDescriptor.dbName_id6DJmAW$7pGu.invoke(fex));
          tgs.append(" ");
          tgs.append(Field__BehaviorDescriptor.sqlType_id6DJmAW$aWx9.invoke(fex));
          tgs.append(" NOT NULL DEFAULT NOW()");
        }
        if ((boolean) Field__BehaviorDescriptor.hasAnotation_id6DJmAW$hoUl.invoke(fex, "nullable")) {
          tgs.append(" ");
          tgs.append(Field__BehaviorDescriptor.dbName_id6DJmAW$7pGu.invoke(fex));
          tgs.append(" ");
          tgs.append(Field__BehaviorDescriptor.sqlType_id6DJmAW$aWx9.invoke(fex));
        }
        if (!((boolean) Field__BehaviorDescriptor.hasAnotation_id6DJmAW$hoUl.invoke(fex, "auto")) && !((boolean) Field__BehaviorDescriptor.hasAnotation_id6DJmAW$hoUl.invoke(fex, "nullable"))) {
          tgs.append(" ");
          tgs.append(Field__BehaviorDescriptor.dbName_id6DJmAW$7pGu.invoke(fex));
          tgs.append(" ");
          tgs.append(Field__BehaviorDescriptor.sqlType_id6DJmAW$aWx9.invoke(fex));
          tgs.append(" NOT NULL");
        }
      }
      tgs.append(",");
      tgs.newLine();
      tgs.append(" PRIMARY KEY (");
      tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(r, LINKS.from$R$Po), PROPS.name$MnvL).toLowerCase());
      tgs.append("_id, ");
      tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(r, LINKS.to$R_jq), PROPS.name$MnvL).toLowerCase());
      tgs.append("_id)");
      tgs.newLine();
      tgs.append(");");
      tgs.newLine();
      tgs.newLine();
    }
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
    /*package*/ static final SProperty dbSchema$kn9b = MetaAdapterFactory.getProperty(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f243a4eceL, 0x6a6f5a6f243a4ed2L, "dbSchema");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink entity$k9hN = MetaAdapterFactory.getReferenceLink(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f243a4ec1L, 0x6a6f5a6f243a4ec2L, "entity");
    /*package*/ static final SContainmentLink fields$Rrud = MetaAdapterFactory.getContainmentLink(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac7eL, 0x6a6f5a6f2407ac84L, "fields");
    /*package*/ static final SContainmentLink entityrefs$ko5f = MetaAdapterFactory.getContainmentLink(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f243a4eceL, 0x6a6f5a6f243a4ed6L, "entityrefs");
    /*package*/ static final SReferenceLink relation$kafN = MetaAdapterFactory.getReferenceLink(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f243a4ec5L, 0x6a6f5a6f243a4ec6L, "relation");
    /*package*/ static final SReferenceLink from$R$Po = MetaAdapterFactory.getReferenceLink(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac8fL, 0x6a6f5a6f2407ac95L, "from");
    /*package*/ static final SReferenceLink to$R_jq = MetaAdapterFactory.getReferenceLink(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac8fL, 0x6a6f5a6f2407ac97L, "to");
    /*package*/ static final SContainmentLink extraFields$RLJf = MetaAdapterFactory.getContainmentLink(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac8fL, 0x6a6f5a6f2407aca2L, "extraFields");
    /*package*/ static final SContainmentLink relations$kokg = MetaAdapterFactory.getContainmentLink(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f243a4eceL, 0x6a6f5a6f243a4ed7L, "relations");
  }
}
