package UserManagement.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenAspectBase;
import UserManagement.structure.LanguageConceptSwitch;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.text.rt.TextGenDescriptor;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.text.rt.TextGenModelOutline;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public class TextGenAspectDescriptor extends TextGenAspectBase {
  private final LanguageConceptSwitch myIndex = new LanguageConceptSwitch();

  public TextGenAspectDescriptor() {
  }

  @Nullable
  @Override
  public TextGenDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    switch (myIndex.index(concept)) {
      case LanguageConceptSwitch.Entity:
        return new Entity_TextGen();
      case LanguageConceptSwitch.Main:
        return new Main_TextGen();
      case LanguageConceptSwitch.Relation:
        return new Relation_TextGen();
      case LanguageConceptSwitch.SqlSchem:
        return new SqlSchem_TextGen();
    }
    return null;
  }

  @Override
  public void breakdownToUnits(@NotNull TextGenModelOutline outline) {
    for (SNode root : outline.getModel().getRootNodes()) {
      if (root.getConcept().equals(CONCEPTS.SqlSchem$b0)) {
        String fname = getFileName_SqlSchem(root);
        String ext = getFileExtension_SqlSchem(root);
        outline.registerTextUnit((ext == null ? fname : (fname + '.' + ext)), root);
        continue;
      }
      if (root.getConcept().equals(CONCEPTS.Entity$iI)) {
        String fname = getFileName_Entity(root);
        String ext = getFileExtension_Entity(root);
        outline.registerTextUnit((ext == null ? fname : (fname + '.' + ext)), getPath_Entity(root), root);
        continue;
      }
      if (root.getConcept().equals(CONCEPTS.Main$eN)) {
        String fname = getFileName_Main(root);
        String ext = getFileExtension_Main(root);
        outline.registerTextUnit((ext == null ? fname : (fname + '.' + ext)), getPath_Main(root), root);
        continue;
      }
    }
  }
  private static String getFileName_SqlSchem(SNode node) {
    return SPropertyOperations.getString(node, PROPS.name$MnvL) + "_init_sql.sql";
  }
  private static String getFileName_Entity(SNode node) {
    return SPropertyOperations.getString(node, PROPS.name$MnvL).toLowerCase();
  }
  private static String getFileName_Main(SNode node) {
    return "main";
  }
  private static String getFileExtension_SqlSchem(SNode node) {
    return null;
  }
  private static String getFileExtension_Entity(SNode node) {
    return "go";
  }
  private static String getFileExtension_Main(SNode node) {
    return "go";
  }
  private static String getPath_Entity(SNode node) {
    return "/src/";
  }
  private static String getPath_Main(SNode node) {
    return "/src/";
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept SqlSchem$b0 = MetaAdapterFactory.getConcept(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f243a4eceL, "UserManagement.structure.SqlSchem");
    /*package*/ static final SConcept Entity$iI = MetaAdapterFactory.getConcept(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac7eL, "UserManagement.structure.Entity");
    /*package*/ static final SConcept Main$eN = MetaAdapterFactory.getConcept(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac21L, "UserManagement.structure.Main");
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
  }
}
