package UserManagement.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractNonTypesystemRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.NonTypesystemRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SEnumOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.errors.messageTargets.MessageTarget;
import jetbrains.mps.errors.messageTargets.NodeMessageTarget;
import jetbrains.mps.errors.IErrorReporter;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SConcept;

public class check_field_annotation_conflicts_NonTypesystemRule extends AbstractNonTypesystemRule_Runtime implements NonTypesystemRule_Runtime {
  public check_field_annotation_conflicts_NonTypesystemRule() {
  }
  public void applyRule(final SNode field, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    boolean hasRequired = false;
    boolean hasNullable = false;
    boolean hasPrimaryKey = false;
    boolean hasAuto = false;
    boolean hasUnique = false;


    for (SNode an : ListSequence.fromList(SLinkOperations.getChildren(field, LINKS.anotations$R8V0))) {
      String n = SEnumOperations.getMemberName0(SPropertyOperations.getEnum(an, PROPS.annotation$RdBN));
      if (n.equals("required")) {
        hasRequired = true;
      }
      if (n.equals("nullable")) {
        hasNullable = true;
      }
      if (n.equals("primaryKey")) {
        hasPrimaryKey = true;
      }
      if (n.equals("auto")) {
        hasAuto = true;
      }
      if (n.equals("unique")) {
        hasUnique = true;
      }
    }

    if (hasRequired && hasNullable) {
      {
        final MessageTarget errorTarget = new NodeMessageTarget();
        IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(field, "Field cannot be both required and nullable", "r:8a1d4cab-7601-4f35-bfa0-5a8a09dfdb29(UserManagement.typesystem)", "7669448123831955027", null, errorTarget);
      }
    }
    if (hasPrimaryKey && hasNullable) {
      {
        final MessageTarget errorTarget = new NodeMessageTarget();
        IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(field, "Primary key field cannot be nullable", "r:8a1d4cab-7601-4f35-bfa0-5a8a09dfdb29(UserManagement.typesystem)", "7669448123831956453", null, errorTarget);
      }
    }
    if (hasAuto && hasRequired) {
      {
        final MessageTarget errorTarget = new NodeMessageTarget();
        IErrorReporter _reporter_2309309498 = typeCheckingContext.reportWarning(field, "Auto-generated field should not be marked required", "r:8a1d4cab-7601-4f35-bfa0-5a8a09dfdb29(UserManagement.typesystem)", "7669448123831966130", null, errorTarget);
      }
    }
    if (hasPrimaryKey && hasUnique) {
      {
        final MessageTarget errorTarget = new NodeMessageTarget();
        IErrorReporter _reporter_2309309498 = typeCheckingContext.reportWarning(field, "Primary key is already unique — redundant", "r:8a1d4cab-7601-4f35-bfa0-5a8a09dfdb29(UserManagement.typesystem)", "7669448123831967761", null, errorTarget);
      }
    }



  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.Field$Sp;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }

  private static final class PROPS {
    /*package*/ static final SProperty annotation$RdBN = MetaAdapterFactory.getProperty(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac73L, 0x6a6f5a6f2407ac74L, "annotation");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink anotations$R8V0 = MetaAdapterFactory.getContainmentLink(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac68L, 0x6a6f5a6f2407ac76L, "anotations");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Field$Sp = MetaAdapterFactory.getConcept(0x2fbdea0625174783L, 0x91c4fb1f5af2c6d7L, 0x6a6f5a6f2407ac68L, "UserManagement.structure.Field");
  }
}
